---
apiVersion: v1
kind: Namespace
metadata:
  name: egress-test
---
apiVersion: v1
kind: Pod
metadata:
  name: test-client
  namespace: egress-test
spec:
  containers:
    - name: curl
      image: curlimages/curl:latest
      command: ["sleep", "infinity"]
  restartPolicy: Never
