---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: threat-policy-manager-role
rules:
- apiGroups:
  - extensions.kuadrant.io
  resources:
  - threatpolicies
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - extensions.kuadrant.io
  resources:
  - threatpolicies/finalizers
  verbs:
  - update
- apiGroups:
  - extensions.kuadrant.io
  resources:
  - threatpolicies/status
  verbs:
  - get
  - patch
  - update
