# Find more at https://docs.codecov.com/docs/codecovyml-reference
codecov:
  bot: "Codecov Bot"
  max_report_age: 12
  require_ci_to_pass: true
  notify:
    after_n_builds: 1
    wait_for_ci: true

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 3%
    patch:
      default:
        target: auto
        threshold: 3%

# Layout of the PR comment produced by Codecov bot
comment:
  layout: "header, diff, flags, components, files"

# Find more at https://docs.codecov.com/docs/ignoring-paths
ignore:
  - api/external/**  #  ignoring external vendor code
  - "**/*.deepcopy.go"  # ignore controller-gen generated code

component_management:
  individual_components:
    - component_id: api-v1beta1
      name: api/v1beta1 (u)
      paths:
        - api/v1beta1
    - component_id: api-v1beta2
      name: api/v1beta2 (u)
      paths:
        - api/v1beta2
    - component_id: common
      name: pkg/common (u)
      paths:
        - pkg/common
    - component_id: istio
      name: pkg/istio (u)
      paths:
        - pkg/istio
    - component_id: log
      name: pkg/log (u)
      paths:
        - pkg/log
    - component_id: reconcilers
      name: pkg/reconcilers (u)
      paths:
        - pkg/reconcilers
    - component_id: rlptools
      name: pkg/rlptools (u)
      paths:
        - pkg/rlptools
    - component_id: controllers
      name: controllers (i)
      paths:
        - controllers
