run:
  timeout: 5m

linters:
  enable:
    - asciicheck
    - errorlint
    - revive
    - gosec
    - stylecheck
    - prealloc
    - tparallel
    - unconvert
    - unparam
    - whitespace
    - goimports
  disable:
    - errcheck

issues:
  exclude-rules:
    # This check has quite a few false positives where there isn't much value in the package comment.
    - text: "ST1000: at least one file in a package should have a package comment"
      linters:
        - stylecheck
    - text: "var-naming: don't use leading k in Go names"
      linters:
        - revive

linters-settings:
  goimports:
    local-prefixes: github.com/kuadrant/kuadrant-operator
