version: "2"
linters:
  enable:
    - asciicheck
    - errorlint
    - gosec
    - prealloc
    - revive
    - staticcheck
    - tparallel
    - unconvert
    - unparam
    - whitespace
  disable:
    - errcheck
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - staticcheck
        text: 'ST1000: at least one file in a package should have a package comment'
      - linters:
          - revive
        text: 'var-naming: don''t use leading k in Go names'
      - linters:
          - revive
        text: 'var-naming: avoid meaningless package names'
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - goimports
  settings:
    # This check has quite a few false positives where there isn't much value in the package comment.
    goimports:
      local-prefixes:
        - github.com/kuadrant/kuadrant-operator
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
