apiVersion: v1
kind: ConfigMap
metadata:
  name: console-plugin-images
  namespace: system
  labels:
    kuadrant-operator-console-plugin-images: "true"
data:
  "4.16": "quay.io/kuadrant/console-plugin:v0.1.5"
  "4.17": "quay.io/kuadrant/console-plugin:v0.1.5"
  "4.18": "quay.io/kuadrant/console-plugin:v0.1.5"
  "4.19": "quay.io/kuadrant/console-plugin:v0.1.5"
  "4.20": "quay.io/kuadrant/console-plugin:latest"
  "default": "quay.io/kuadrant/console-plugin:latest"
