---
apiVersion: v1
kind: Service
metadata:
  labels:
    control-plane: controller-manager
  name: ecds
  namespace: system
spec:
  ports:
  - name: ecds
    port: 50053
    protocol: TCP
    targetPort: ecds
  selector:
    control-plane: controller-manager
