---
apiVersion: v1
kind: Service
metadata:
  labels:
    control-plane: controller-manager
  name: metrics
  namespace: system
spec:
  ports:
  - name: metrics
    port: 8080
    targetPort: metrics
  selector:
    control-plane: controller-manager
