//go:build !ignore_autogenerated

/*
Copyright 2021.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	certmanagerv1 "github.com/cert-manager/cert-manager/pkg/apis/certmanager/v1"
	"github.com/kuadrant/authorino/api/v1beta3"
	"github.com/kuadrant/dns-operator/api/v1alpha1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuthPolicy) DeepCopyInto(out *AuthPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuthPolicy.
func (in *AuthPolicy) DeepCopy() *AuthPolicy {
	if in == nil {
		return nil
	}
	out := new(AuthPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AuthPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuthPolicyList) DeepCopyInto(out *AuthPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AuthPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuthPolicyList.
func (in *AuthPolicyList) DeepCopy() *AuthPolicyList {
	if in == nil {
		return nil
	}
	out := new(AuthPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AuthPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuthPolicySpec) DeepCopyInto(out *AuthPolicySpec) {
	*out = *in
	in.TargetRef.DeepCopyInto(&out.TargetRef)
	if in.Defaults != nil {
		in, out := &in.Defaults, &out.Defaults
		*out = new(MergeableAuthPolicySpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Overrides != nil {
		in, out := &in.Overrides, &out.Overrides
		*out = new(MergeableAuthPolicySpec)
		(*in).DeepCopyInto(*out)
	}
	in.AuthPolicySpecProper.DeepCopyInto(&out.AuthPolicySpecProper)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuthPolicySpec.
func (in *AuthPolicySpec) DeepCopy() *AuthPolicySpec {
	if in == nil {
		return nil
	}
	out := new(AuthPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuthPolicySpecProper) DeepCopyInto(out *AuthPolicySpecProper) {
	*out = *in
	if in.NamedPatterns != nil {
		in, out := &in.NamedPatterns, &out.NamedPatterns
		*out = make(map[string]MergeablePatternExpressions, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	in.MergeableWhenPredicates.DeepCopyInto(&out.MergeableWhenPredicates)
	if in.AuthScheme != nil {
		in, out := &in.AuthScheme, &out.AuthScheme
		*out = new(AuthSchemeSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuthPolicySpecProper.
func (in *AuthPolicySpecProper) DeepCopy() *AuthPolicySpecProper {
	if in == nil {
		return nil
	}
	out := new(AuthPolicySpecProper)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuthPolicyStatus) DeepCopyInto(out *AuthPolicyStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuthPolicyStatus.
func (in *AuthPolicyStatus) DeepCopy() *AuthPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(AuthPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuthSchemeSpec) DeepCopyInto(out *AuthSchemeSpec) {
	*out = *in
	if in.Authentication != nil {
		in, out := &in.Authentication, &out.Authentication
		*out = make(map[string]MergeableAuthenticationSpec, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.Metadata != nil {
		in, out := &in.Metadata, &out.Metadata
		*out = make(map[string]MergeableMetadataSpec, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.Authorization != nil {
		in, out := &in.Authorization, &out.Authorization
		*out = make(map[string]MergeableAuthorizationSpec, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.Response != nil {
		in, out := &in.Response, &out.Response
		*out = new(MergeableResponseSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Callbacks != nil {
		in, out := &in.Callbacks, &out.Callbacks
		*out = make(map[string]MergeableCallbackSpec, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuthSchemeSpec.
func (in *AuthSchemeSpec) DeepCopy() *AuthSchemeSpec {
	if in == nil {
		return nil
	}
	out := new(AuthSchemeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CertificateSpec) DeepCopyInto(out *CertificateSpec) {
	*out = *in
	out.IssuerRef = in.IssuerRef
	if in.Duration != nil {
		in, out := &in.Duration, &out.Duration
		*out = new(metav1.Duration)
		**out = **in
	}
	if in.RenewBefore != nil {
		in, out := &in.RenewBefore, &out.RenewBefore
		*out = new(metav1.Duration)
		**out = **in
	}
	if in.Usages != nil {
		in, out := &in.Usages, &out.Usages
		*out = make([]certmanagerv1.KeyUsage, len(*in))
		copy(*out, *in)
	}
	if in.RevisionHistoryLimit != nil {
		in, out := &in.RevisionHistoryLimit, &out.RevisionHistoryLimit
		*out = new(int32)
		**out = **in
	}
	if in.PrivateKey != nil {
		in, out := &in.PrivateKey, &out.PrivateKey
		*out = new(certmanagerv1.CertificatePrivateKey)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CertificateSpec.
func (in *CertificateSpec) DeepCopy() *CertificateSpec {
	if in == nil {
		return nil
	}
	out := new(CertificateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Counter) DeepCopyInto(out *Counter) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Counter.
func (in *Counter) DeepCopy() *Counter {
	if in == nil {
		return nil
	}
	out := new(Counter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DNSPolicy) DeepCopyInto(out *DNSPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DNSPolicy.
func (in *DNSPolicy) DeepCopy() *DNSPolicy {
	if in == nil {
		return nil
	}
	out := new(DNSPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DNSPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DNSPolicyList) DeepCopyInto(out *DNSPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DNSPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DNSPolicyList.
func (in *DNSPolicyList) DeepCopy() *DNSPolicyList {
	if in == nil {
		return nil
	}
	out := new(DNSPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DNSPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DNSPolicySpec) DeepCopyInto(out *DNSPolicySpec) {
	*out = *in
	in.TargetRef.DeepCopyInto(&out.TargetRef)
	if in.HealthCheck != nil {
		in, out := &in.HealthCheck, &out.HealthCheck
		*out = new(v1alpha1.HealthCheckSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.LoadBalancing != nil {
		in, out := &in.LoadBalancing, &out.LoadBalancing
		*out = new(LoadBalancingSpec)
		**out = **in
	}
	if in.ProviderRefs != nil {
		in, out := &in.ProviderRefs, &out.ProviderRefs
		*out = make([]v1alpha1.ProviderRef, len(*in))
		copy(*out, *in)
	}
	if in.ExcludeAddresses != nil {
		in, out := &in.ExcludeAddresses, &out.ExcludeAddresses
		*out = make(ExcludeAddresses, len(*in))
		copy(*out, *in)
	}
	if in.AuthorityDelegation != nil {
		in, out := &in.AuthorityDelegation, &out.AuthorityDelegation
		*out = new(v1alpha1.AuthorityDelegation)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DNSPolicySpec.
func (in *DNSPolicySpec) DeepCopy() *DNSPolicySpec {
	if in == nil {
		return nil
	}
	out := new(DNSPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DNSPolicyStatus) DeepCopyInto(out *DNSPolicyStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.HealthCheck != nil {
		in, out := &in.HealthCheck, &out.HealthCheck
		*out = new(v1alpha1.HealthCheckStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.RecordConditions != nil {
		in, out := &in.RecordConditions, &out.RecordConditions
		*out = make(map[string][]metav1.Condition, len(*in))
		for key, val := range *in {
			var outVal []metav1.Condition
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = make([]metav1.Condition, len(*in))
				for i := range *in {
					(*in)[i].DeepCopyInto(&(*out)[i])
				}
			}
			(*out)[key] = outVal
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DNSPolicyStatus.
func (in *DNSPolicyStatus) DeepCopy() *DNSPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(DNSPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in ExcludeAddresses) DeepCopyInto(out *ExcludeAddresses) {
	{
		in := &in
		*out = make(ExcludeAddresses, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExcludeAddresses.
func (in ExcludeAddresses) DeepCopy() ExcludeAddresses {
	if in == nil {
		return nil
	}
	out := new(ExcludeAddresses)
	in.DeepCopyInto(out)
	return *out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Limit) DeepCopyInto(out *Limit) {
	*out = *in
	if in.When != nil {
		in, out := &in.When, &out.When
		*out = make(WhenPredicates, len(*in))
		copy(*out, *in)
	}
	if in.Counters != nil {
		in, out := &in.Counters, &out.Counters
		*out = make([]Counter, len(*in))
		copy(*out, *in)
	}
	if in.Rates != nil {
		in, out := &in.Rates, &out.Rates
		*out = make([]Rate, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Limit.
func (in *Limit) DeepCopy() *Limit {
	if in == nil {
		return nil
	}
	out := new(Limit)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoadBalancingSpec) DeepCopyInto(out *LoadBalancingSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoadBalancingSpec.
func (in *LoadBalancingSpec) DeepCopy() *LoadBalancingSpec {
	if in == nil {
		return nil
	}
	out := new(LoadBalancingSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MergeableAuthPolicySpec) DeepCopyInto(out *MergeableAuthPolicySpec) {
	*out = *in
	in.AuthPolicySpecProper.DeepCopyInto(&out.AuthPolicySpecProper)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MergeableAuthPolicySpec.
func (in *MergeableAuthPolicySpec) DeepCopy() *MergeableAuthPolicySpec {
	if in == nil {
		return nil
	}
	out := new(MergeableAuthPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MergeableAuthenticationSpec) DeepCopyInto(out *MergeableAuthenticationSpec) {
	*out = *in
	in.AuthenticationSpec.DeepCopyInto(&out.AuthenticationSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MergeableAuthenticationSpec.
func (in *MergeableAuthenticationSpec) DeepCopy() *MergeableAuthenticationSpec {
	if in == nil {
		return nil
	}
	out := new(MergeableAuthenticationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MergeableAuthorizationSpec) DeepCopyInto(out *MergeableAuthorizationSpec) {
	*out = *in
	in.AuthorizationSpec.DeepCopyInto(&out.AuthorizationSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MergeableAuthorizationSpec.
func (in *MergeableAuthorizationSpec) DeepCopy() *MergeableAuthorizationSpec {
	if in == nil {
		return nil
	}
	out := new(MergeableAuthorizationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MergeableCallbackSpec) DeepCopyInto(out *MergeableCallbackSpec) {
	*out = *in
	in.CallbackSpec.DeepCopyInto(&out.CallbackSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MergeableCallbackSpec.
func (in *MergeableCallbackSpec) DeepCopy() *MergeableCallbackSpec {
	if in == nil {
		return nil
	}
	out := new(MergeableCallbackSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MergeableDenyWithSpec) DeepCopyInto(out *MergeableDenyWithSpec) {
	*out = *in
	in.DenyWithSpec.DeepCopyInto(&out.DenyWithSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MergeableDenyWithSpec.
func (in *MergeableDenyWithSpec) DeepCopy() *MergeableDenyWithSpec {
	if in == nil {
		return nil
	}
	out := new(MergeableDenyWithSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MergeableHeaderSuccessResponseSpec) DeepCopyInto(out *MergeableHeaderSuccessResponseSpec) {
	*out = *in
	in.HeaderSuccessResponseSpec.DeepCopyInto(&out.HeaderSuccessResponseSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MergeableHeaderSuccessResponseSpec.
func (in *MergeableHeaderSuccessResponseSpec) DeepCopy() *MergeableHeaderSuccessResponseSpec {
	if in == nil {
		return nil
	}
	out := new(MergeableHeaderSuccessResponseSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MergeableMetadataSpec) DeepCopyInto(out *MergeableMetadataSpec) {
	*out = *in
	in.MetadataSpec.DeepCopyInto(&out.MetadataSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MergeableMetadataSpec.
func (in *MergeableMetadataSpec) DeepCopy() *MergeableMetadataSpec {
	if in == nil {
		return nil
	}
	out := new(MergeableMetadataSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MergeablePatternExpressions) DeepCopyInto(out *MergeablePatternExpressions) {
	*out = *in
	if in.PatternExpressions != nil {
		in, out := &in.PatternExpressions, &out.PatternExpressions
		*out = make(v1beta3.PatternExpressions, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MergeablePatternExpressions.
func (in *MergeablePatternExpressions) DeepCopy() *MergeablePatternExpressions {
	if in == nil {
		return nil
	}
	out := new(MergeablePatternExpressions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MergeableRateLimitPolicySpec) DeepCopyInto(out *MergeableRateLimitPolicySpec) {
	*out = *in
	in.RateLimitPolicySpecProper.DeepCopyInto(&out.RateLimitPolicySpecProper)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MergeableRateLimitPolicySpec.
func (in *MergeableRateLimitPolicySpec) DeepCopy() *MergeableRateLimitPolicySpec {
	if in == nil {
		return nil
	}
	out := new(MergeableRateLimitPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MergeableResponseSpec) DeepCopyInto(out *MergeableResponseSpec) {
	*out = *in
	if in.Unauthenticated != nil {
		in, out := &in.Unauthenticated, &out.Unauthenticated
		*out = new(MergeableDenyWithSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Unauthorized != nil {
		in, out := &in.Unauthorized, &out.Unauthorized
		*out = new(MergeableDenyWithSpec)
		(*in).DeepCopyInto(*out)
	}
	in.Success.DeepCopyInto(&out.Success)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MergeableResponseSpec.
func (in *MergeableResponseSpec) DeepCopy() *MergeableResponseSpec {
	if in == nil {
		return nil
	}
	out := new(MergeableResponseSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MergeableSuccessResponseSpec) DeepCopyInto(out *MergeableSuccessResponseSpec) {
	*out = *in
	in.SuccessResponseSpec.DeepCopyInto(&out.SuccessResponseSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MergeableSuccessResponseSpec.
func (in *MergeableSuccessResponseSpec) DeepCopy() *MergeableSuccessResponseSpec {
	if in == nil {
		return nil
	}
	out := new(MergeableSuccessResponseSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MergeableWhenPredicates) DeepCopyInto(out *MergeableWhenPredicates) {
	*out = *in
	if in.Predicates != nil {
		in, out := &in.Predicates, &out.Predicates
		*out = make(WhenPredicates, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MergeableWhenPredicates.
func (in *MergeableWhenPredicates) DeepCopy() *MergeableWhenPredicates {
	if in == nil {
		return nil
	}
	out := new(MergeableWhenPredicates)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MergeableWrappedSuccessResponseSpec) DeepCopyInto(out *MergeableWrappedSuccessResponseSpec) {
	*out = *in
	if in.Headers != nil {
		in, out := &in.Headers, &out.Headers
		*out = make(map[string]MergeableHeaderSuccessResponseSpec, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.DynamicMetadata != nil {
		in, out := &in.DynamicMetadata, &out.DynamicMetadata
		*out = make(map[string]MergeableSuccessResponseSpec, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MergeableWrappedSuccessResponseSpec.
func (in *MergeableWrappedSuccessResponseSpec) DeepCopy() *MergeableWrappedSuccessResponseSpec {
	if in == nil {
		return nil
	}
	out := new(MergeableWrappedSuccessResponseSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Predicate) DeepCopyInto(out *Predicate) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Predicate.
func (in *Predicate) DeepCopy() *Predicate {
	if in == nil {
		return nil
	}
	out := new(Predicate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Rate) DeepCopyInto(out *Rate) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Rate.
func (in *Rate) DeepCopy() *Rate {
	if in == nil {
		return nil
	}
	out := new(Rate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RateLimitPolicy) DeepCopyInto(out *RateLimitPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RateLimitPolicy.
func (in *RateLimitPolicy) DeepCopy() *RateLimitPolicy {
	if in == nil {
		return nil
	}
	out := new(RateLimitPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RateLimitPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RateLimitPolicyList) DeepCopyInto(out *RateLimitPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]RateLimitPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RateLimitPolicyList.
func (in *RateLimitPolicyList) DeepCopy() *RateLimitPolicyList {
	if in == nil {
		return nil
	}
	out := new(RateLimitPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RateLimitPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RateLimitPolicySpec) DeepCopyInto(out *RateLimitPolicySpec) {
	*out = *in
	in.TargetRef.DeepCopyInto(&out.TargetRef)
	if in.Defaults != nil {
		in, out := &in.Defaults, &out.Defaults
		*out = new(MergeableRateLimitPolicySpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Overrides != nil {
		in, out := &in.Overrides, &out.Overrides
		*out = new(MergeableRateLimitPolicySpec)
		(*in).DeepCopyInto(*out)
	}
	in.RateLimitPolicySpecProper.DeepCopyInto(&out.RateLimitPolicySpecProper)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RateLimitPolicySpec.
func (in *RateLimitPolicySpec) DeepCopy() *RateLimitPolicySpec {
	if in == nil {
		return nil
	}
	out := new(RateLimitPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RateLimitPolicySpecProper) DeepCopyInto(out *RateLimitPolicySpecProper) {
	*out = *in
	in.MergeableWhenPredicates.DeepCopyInto(&out.MergeableWhenPredicates)
	if in.Limits != nil {
		in, out := &in.Limits, &out.Limits
		*out = make(map[string]Limit, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RateLimitPolicySpecProper.
func (in *RateLimitPolicySpecProper) DeepCopy() *RateLimitPolicySpecProper {
	if in == nil {
		return nil
	}
	out := new(RateLimitPolicySpecProper)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RateLimitPolicyStatus) DeepCopyInto(out *RateLimitPolicyStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RateLimitPolicyStatus.
func (in *RateLimitPolicyStatus) DeepCopy() *RateLimitPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(RateLimitPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TLSPolicy) DeepCopyInto(out *TLSPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TLSPolicy.
func (in *TLSPolicy) DeepCopy() *TLSPolicy {
	if in == nil {
		return nil
	}
	out := new(TLSPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TLSPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TLSPolicyList) DeepCopyInto(out *TLSPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]TLSPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TLSPolicyList.
func (in *TLSPolicyList) DeepCopy() *TLSPolicyList {
	if in == nil {
		return nil
	}
	out := new(TLSPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TLSPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TLSPolicySpec) DeepCopyInto(out *TLSPolicySpec) {
	*out = *in
	in.TargetRef.DeepCopyInto(&out.TargetRef)
	in.CertificateSpec.DeepCopyInto(&out.CertificateSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TLSPolicySpec.
func (in *TLSPolicySpec) DeepCopy() *TLSPolicySpec {
	if in == nil {
		return nil
	}
	out := new(TLSPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TLSPolicyStatus) DeepCopyInto(out *TLSPolicyStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TLSPolicyStatus.
func (in *TLSPolicyStatus) DeepCopy() *TLSPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(TLSPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in WhenPredicates) DeepCopyInto(out *WhenPredicates) {
	{
		in := &in
		*out = make(WhenPredicates, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WhenPredicates.
func (in WhenPredicates) DeepCopy() WhenPredicates {
	if in == nil {
		return nil
	}
	out := new(WhenPredicates)
	in.DeepCopyInto(out)
	return *out
}
