resources:
- github.com/kuadrant/dns-operator/config/default?ref=${DNS_OPERATOR_GITREF}

patches:
  - path: deployment_patch.yaml
    target:
      kind: Deployment
      name: dns-operator-controller-manager

images:
  - name: quay.io/kuadrant/dns-operator
    newName: quay.io/kuadrant/dns-operator
    newTag: ${DNS_OPERATOR_GITREF}
