apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: null
  labels:
    app: developer-portal-controller
    kuadrant.io/developerportal: "true"
  name: developer-portal-controller-manager
