apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  labels:
    app: kuadrant
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: kuadrant-operator
  name: kuadrant-operator-oidcpolicy-viewer-role
rules:
- apiGroups:
  - kuadrant.io
  resources:
  - oidcpolicies
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kuadrant.io
  resources:
  - oidcpolicies/status
  verbs:
  - get
