apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: kuadrant
    control-plane: controller-manager
  name: kuadrant-operator-controller-manager-ratelimit-wasm-service
spec:
  ports:
  - name: ratelimit-wasm
    port: 8082
    targetPort: ratelimit-wasm
  selector:
    app: kuadrant
    control-plane: controller-manager
status:
  loadBalancer: {}
