apiVersion: v1
data:
  "4.16": quay.io/kuadrant/console-plugin:v0.1.5
  "4.17": quay.io/kuadrant/console-plugin:v0.1.5
  "4.18": quay.io/kuadrant/console-plugin:v0.1.5
  "4.19": quay.io/kuadrant/console-plugin:v0.1.5
  "4.20": quay.io/kuadrant/console-plugin:latest
  default: quay.io/kuadrant/console-plugin:latest
kind: ConfigMap
metadata:
  labels:
    app: kuadrant
    kuadrant-operator-console-plugin-images: "true"
  name: kuadrant-operator-console-plugin-images
