apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  labels:
    app: kuadrant
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: kuadrant-operator
  name: kuadrant-operator-oidcmetapolicy-editor-role
rules:
- apiGroups:
  - kuadrant.io
  resources:
  - oidcmetapolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kuadrant.io
  resources:
  - oidcmetapolicies/status
  verbs:
  - get
