apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: kuadrant
    control-plane: controller-manager
  name: kuadrant-operator-controller-manager-wasm-shim-service
spec:
  ports:
  - name: wasm-shim
    port: 8082
    targetPort: wasm-shim
  selector:
    app: kuadrant
    control-plane: controller-manager
status:
  loadBalancer: {}
