apiVersion: v1
kind: Secret
metadata:
  name: admin-api-keys
  labels:
    app: grpcbin
    role: admin
    authorino.kuadrant.io/managed-by: authorino
stringData:
  api_key: ADMINKEY456
type: Opaque
