---
apiVersion: v1
kind: Secret
metadata:
  annotations:
    secret.kuadrant.io/user-id: grpcuser
  labels:
    app: grpcbin
    authorino.kuadrant.io/managed-by: authorino
  name: grpcbin-apikey
stringData:
  api_key: GRPCBINKEY123
type: Opaque
