apiVersion: sailoperator.io/v1
kind: Istio
metadata:
  name: default
spec:
  # Supported values for sail-operator v1.29.1 are:
  # - v1.29-latest
  # - v1.29.1
  # - v1.29.0
  # - v1.28-latest
  # - v1.28.5
  # - v1.28.4
  # - v1.28.3
  # - v1.28.2
  # - v1.28.1
  # - v1.28.0
  # - v1.27-latest
  # - v1.27.8
  # - v1.27.7
  # - v1.27.6
  # Minimum version for Gateway API v1.5 spec.tls.frontend support: v1.28.0
  version: v1.29.1
  namespace: istio-system
  # Disable autoscaling to reduce dev resources
  values:
    pilot:
      autoscaleEnabled: false
