apiVersion: operator.istio.io/v1alpha1
kind: Istio
metadata:
  name: default
spec:
  version: v1.20.0
  namespace: istio-system
  # Disable autoscaling to reduce dev resources
  values:
    pilot:
      env:
        PILOT_ENABLE_ALPHA_GATEWAY_API: "true"
      autoscaleEnabled: false
  rawValues:
    gateways:
      istio-ingressgateway:
        autoscaleEnabled: false
