apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "developer-portal-controller.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "developer-portal-controller.labels" . | nindent 4 }}
