// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: v1/descriptor_service.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetServiceDescriptorsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Services      []*ServiceRef          `protobuf:"bytes,1,rep,name=services,proto3" json:"services,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetServiceDescriptorsRequest) Reset() {
	*x = GetServiceDescriptorsRequest{}
	mi := &file_v1_descriptor_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetServiceDescriptorsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServiceDescriptorsRequest) ProtoMessage() {}

func (x *GetServiceDescriptorsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_descriptor_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServiceDescriptorsRequest.ProtoReflect.Descriptor instead.
func (*GetServiceDescriptorsRequest) Descriptor() ([]byte, []int) {
	return file_v1_descriptor_service_proto_rawDescGZIP(), []int{0}
}

func (x *GetServiceDescriptorsRequest) GetServices() []*ServiceRef {
	if x != nil {
		return x.Services
	}
	return nil
}

type ServiceRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClusterName   string                 `protobuf:"bytes,1,opt,name=cluster_name,json=clusterName,proto3" json:"cluster_name,omitempty"`
	Service       string                 `protobuf:"bytes,2,opt,name=service,proto3" json:"service,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceRef) Reset() {
	*x = ServiceRef{}
	mi := &file_v1_descriptor_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceRef) ProtoMessage() {}

func (x *ServiceRef) ProtoReflect() protoreflect.Message {
	mi := &file_v1_descriptor_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceRef.ProtoReflect.Descriptor instead.
func (*ServiceRef) Descriptor() ([]byte, []int) {
	return file_v1_descriptor_service_proto_rawDescGZIP(), []int{1}
}

func (x *ServiceRef) GetClusterName() string {
	if x != nil {
		return x.ClusterName
	}
	return ""
}

func (x *ServiceRef) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

type GetServiceDescriptorsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Descriptors   []*ServiceDescriptor   `protobuf:"bytes,1,rep,name=descriptors,proto3" json:"descriptors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetServiceDescriptorsResponse) Reset() {
	*x = GetServiceDescriptorsResponse{}
	mi := &file_v1_descriptor_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetServiceDescriptorsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServiceDescriptorsResponse) ProtoMessage() {}

func (x *GetServiceDescriptorsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_descriptor_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServiceDescriptorsResponse.ProtoReflect.Descriptor instead.
func (*GetServiceDescriptorsResponse) Descriptor() ([]byte, []int) {
	return file_v1_descriptor_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetServiceDescriptorsResponse) GetDescriptors() []*ServiceDescriptor {
	if x != nil {
		return x.Descriptors
	}
	return nil
}

type ServiceDescriptor struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ClusterName       string                 `protobuf:"bytes,1,opt,name=cluster_name,json=clusterName,proto3" json:"cluster_name,omitempty"`
	Service           string                 `protobuf:"bytes,2,opt,name=service,proto3" json:"service,omitempty"`
	FileDescriptorSet []byte                 `protobuf:"bytes,3,opt,name=file_descriptor_set,json=fileDescriptorSet,proto3" json:"file_descriptor_set,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ServiceDescriptor) Reset() {
	*x = ServiceDescriptor{}
	mi := &file_v1_descriptor_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceDescriptor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceDescriptor) ProtoMessage() {}

func (x *ServiceDescriptor) ProtoReflect() protoreflect.Message {
	mi := &file_v1_descriptor_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceDescriptor.ProtoReflect.Descriptor instead.
func (*ServiceDescriptor) Descriptor() ([]byte, []int) {
	return file_v1_descriptor_service_proto_rawDescGZIP(), []int{3}
}

func (x *ServiceDescriptor) GetClusterName() string {
	if x != nil {
		return x.ClusterName
	}
	return ""
}

func (x *ServiceDescriptor) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *ServiceDescriptor) GetFileDescriptorSet() []byte {
	if x != nil {
		return x.FileDescriptorSet
	}
	return nil
}

var File_v1_descriptor_service_proto protoreflect.FileDescriptor

const file_v1_descriptor_service_proto_rawDesc = "" +
	"\n" +
	"\x1bv1/descriptor_service.proto\x12\vkuadrant.v1\"S\n" +
	"\x1cGetServiceDescriptorsRequest\x123\n" +
	"\bservices\x18\x01 \x03(\v2\x17.kuadrant.v1.ServiceRefR\bservices\"I\n" +
	"\n" +
	"ServiceRef\x12!\n" +
	"\fcluster_name\x18\x01 \x01(\tR\vclusterName\x12\x18\n" +
	"\aservice\x18\x02 \x01(\tR\aservice\"a\n" +
	"\x1dGetServiceDescriptorsResponse\x12@\n" +
	"\vdescriptors\x18\x01 \x03(\v2\x1e.kuadrant.v1.ServiceDescriptorR\vdescriptors\"\x80\x01\n" +
	"\x11ServiceDescriptor\x12!\n" +
	"\fcluster_name\x18\x01 \x01(\tR\vclusterName\x12\x18\n" +
	"\aservice\x18\x02 \x01(\tR\aservice\x12.\n" +
	"\x13file_descriptor_set\x18\x03 \x01(\fR\x11fileDescriptorSet2\x85\x01\n" +
	"\x11DescriptorService\x12p\n" +
	"\x15GetServiceDescriptors\x12).kuadrant.v1.GetServiceDescriptorsRequest\x1a*.kuadrant.v1.GetServiceDescriptorsResponse\"\x00B\x05Z\x03/v1b\x06proto3"

var (
	file_v1_descriptor_service_proto_rawDescOnce sync.Once
	file_v1_descriptor_service_proto_rawDescData []byte
)

func file_v1_descriptor_service_proto_rawDescGZIP() []byte {
	file_v1_descriptor_service_proto_rawDescOnce.Do(func() {
		file_v1_descriptor_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_descriptor_service_proto_rawDesc), len(file_v1_descriptor_service_proto_rawDesc)))
	})
	return file_v1_descriptor_service_proto_rawDescData
}

var file_v1_descriptor_service_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_v1_descriptor_service_proto_goTypes = []any{
	(*GetServiceDescriptorsRequest)(nil),  // 0: kuadrant.v1.GetServiceDescriptorsRequest
	(*ServiceRef)(nil),                    // 1: kuadrant.v1.ServiceRef
	(*GetServiceDescriptorsResponse)(nil), // 2: kuadrant.v1.GetServiceDescriptorsResponse
	(*ServiceDescriptor)(nil),             // 3: kuadrant.v1.ServiceDescriptor
}
var file_v1_descriptor_service_proto_depIdxs = []int32{
	1, // 0: kuadrant.v1.GetServiceDescriptorsRequest.services:type_name -> kuadrant.v1.ServiceRef
	3, // 1: kuadrant.v1.GetServiceDescriptorsResponse.descriptors:type_name -> kuadrant.v1.ServiceDescriptor
	0, // 2: kuadrant.v1.DescriptorService.GetServiceDescriptors:input_type -> kuadrant.v1.GetServiceDescriptorsRequest
	2, // 3: kuadrant.v1.DescriptorService.GetServiceDescriptors:output_type -> kuadrant.v1.GetServiceDescriptorsResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_v1_descriptor_service_proto_init() }
func file_v1_descriptor_service_proto_init() {
	if File_v1_descriptor_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_descriptor_service_proto_rawDesc), len(file_v1_descriptor_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_descriptor_service_proto_goTypes,
		DependencyIndexes: file_v1_descriptor_service_proto_depIdxs,
		MessageInfos:      file_v1_descriptor_service_proto_msgTypes,
	}.Build()
	File_v1_descriptor_service_proto = out.File
	file_v1_descriptor_service_proto_goTypes = nil
	file_v1_descriptor_service_proto_depIdxs = nil
}
