// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: v1/descriptor_service.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DescriptorService_GetServiceDescriptors_FullMethodName = "/kuadrant.v1.DescriptorService/GetServiceDescriptors"
)

// DescriptorServiceClient is the client API for DescriptorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// DescriptorService allows wasm components to retrieve cached protobuf descriptors
// for registered upstream gRPC services.
type DescriptorServiceClient interface {
	GetServiceDescriptors(ctx context.Context, in *GetServiceDescriptorsRequest, opts ...grpc.CallOption) (*GetServiceDescriptorsResponse, error)
}

type descriptorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDescriptorServiceClient(cc grpc.ClientConnInterface) DescriptorServiceClient {
	return &descriptorServiceClient{cc}
}

func (c *descriptorServiceClient) GetServiceDescriptors(ctx context.Context, in *GetServiceDescriptorsRequest, opts ...grpc.CallOption) (*GetServiceDescriptorsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetServiceDescriptorsResponse)
	err := c.cc.Invoke(ctx, DescriptorService_GetServiceDescriptors_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DescriptorServiceServer is the server API for DescriptorService service.
// All implementations must embed UnimplementedDescriptorServiceServer
// for forward compatibility.
//
// DescriptorService allows wasm components to retrieve cached protobuf descriptors
// for registered upstream gRPC services.
type DescriptorServiceServer interface {
	GetServiceDescriptors(context.Context, *GetServiceDescriptorsRequest) (*GetServiceDescriptorsResponse, error)
	mustEmbedUnimplementedDescriptorServiceServer()
}

// UnimplementedDescriptorServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDescriptorServiceServer struct{}

func (UnimplementedDescriptorServiceServer) GetServiceDescriptors(context.Context, *GetServiceDescriptorsRequest) (*GetServiceDescriptorsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetServiceDescriptors not implemented")
}
func (UnimplementedDescriptorServiceServer) mustEmbedUnimplementedDescriptorServiceServer() {}
func (UnimplementedDescriptorServiceServer) testEmbeddedByValue()                           {}

// UnsafeDescriptorServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DescriptorServiceServer will
// result in compilation errors.
type UnsafeDescriptorServiceServer interface {
	mustEmbedUnimplementedDescriptorServiceServer()
}

func RegisterDescriptorServiceServer(s grpc.ServiceRegistrar, srv DescriptorServiceServer) {
	// If the following call panics, it indicates UnimplementedDescriptorServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DescriptorService_ServiceDesc, srv)
}

func _DescriptorService_GetServiceDescriptors_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetServiceDescriptorsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DescriptorServiceServer).GetServiceDescriptors(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DescriptorService_GetServiceDescriptors_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DescriptorServiceServer).GetServiceDescriptors(ctx, req.(*GetServiceDescriptorsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DescriptorService_ServiceDesc is the grpc.ServiceDesc for DescriptorService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DescriptorService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "kuadrant.v1.DescriptorService",
	HandlerType: (*DescriptorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetServiceDescriptors",
			Handler:    _DescriptorService_GetServiceDescriptors_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "v1/descriptor_service.proto",
}
