// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.6
// source: v1/kuadrant.proto

package v1

import (
	empty "github.com/golang/protobuf/ptypes/empty"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	v1alpha1 "google.golang.org/genproto/googleapis/api/expr/v1alpha1"
	status "google.golang.org/genproto/googleapis/rpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Domain int32

const (
	Domain_DOMAIN_UNSPECIFIED Domain = 0
	Domain_DOMAIN_AUTH        Domain = 1
	Domain_DOMAIN_REQUEST     Domain = 2
)

// Enum value maps for Domain.
var (
	Domain_name = map[int32]string{
		0: "DOMAIN_UNSPECIFIED",
		1: "DOMAIN_AUTH",
		2: "DOMAIN_REQUEST",
	}
	Domain_value = map[string]int32{
		"DOMAIN_UNSPECIFIED": 0,
		"DOMAIN_AUTH":        1,
		"DOMAIN_REQUEST":     2,
	}
)

func (x Domain) Enum() *Domain {
	p := new(Domain)
	*p = x
	return p
}

func (x Domain) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Domain) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_kuadrant_proto_enumTypes[0].Descriptor()
}

func (Domain) Type() protoreflect.EnumType {
	return &file_v1_kuadrant_proto_enumTypes[0]
}

func (x Domain) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Domain.Descriptor instead.
func (Domain) EnumDescriptor() ([]byte, []int) {
	return file_v1_kuadrant_proto_rawDescGZIP(), []int{0}
}

// ActionType discriminates how the wasm-shim dispatches an action.
type ActionType int32

const (
	ActionType_ACTION_TYPE_UNSPECIFIED        ActionType = 0
	ActionType_ACTION_TYPE_GRPC_METHOD        ActionType = 1
	ActionType_ACTION_TYPE_ALLOW              ActionType = 2
	ActionType_ACTION_TYPE_ADD_HEADERS        ActionType = 3
	ActionType_ACTION_TYPE_WITH_RESPONSE_CODE ActionType = 4
)

// Enum value maps for ActionType.
var (
	ActionType_name = map[int32]string{
		0: "ACTION_TYPE_UNSPECIFIED",
		1: "ACTION_TYPE_GRPC_METHOD",
		2: "ACTION_TYPE_ALLOW",
		3: "ACTION_TYPE_ADD_HEADERS",
		4: "ACTION_TYPE_WITH_RESPONSE_CODE",
	}
	ActionType_value = map[string]int32{
		"ACTION_TYPE_UNSPECIFIED":        0,
		"ACTION_TYPE_GRPC_METHOD":        1,
		"ACTION_TYPE_ALLOW":              2,
		"ACTION_TYPE_ADD_HEADERS":        3,
		"ACTION_TYPE_WITH_RESPONSE_CODE": 4,
	}
)

func (x ActionType) Enum() *ActionType {
	p := new(ActionType)
	*p = x
	return p
}

func (x ActionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ActionType) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_kuadrant_proto_enumTypes[1].Descriptor()
}

func (ActionType) Type() protoreflect.EnumType {
	return &file_v1_kuadrant_proto_enumTypes[1]
}

func (x ActionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ActionType.Descriptor instead.
func (ActionType) EnumDescriptor() ([]byte, []int) {
	return file_v1_kuadrant_proto_rawDescGZIP(), []int{1}
}

// The request message containing the time the request was dispatched.
type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Out           *timestamp.Timestamp   `protobuf:"bytes,1,opt,name=out,proto3" json:"out,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_v1_kuadrant_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_kuadrant_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_v1_kuadrant_proto_rawDescGZIP(), []int{0}
}

func (x *PingRequest) GetOut() *timestamp.Timestamp {
	if x != nil {
		return x.Out
	}
	return nil
}

// The response message containing the time the request was received.
type PongResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	In            *timestamp.Timestamp   `protobuf:"bytes,1,opt,name=in,proto3" json:"in,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PongResponse) Reset() {
	*x = PongResponse{}
	mi := &file_v1_kuadrant_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PongResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PongResponse) ProtoMessage() {}

func (x *PongResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_kuadrant_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PongResponse.ProtoReflect.Descriptor instead.
func (*PongResponse) Descriptor() ([]byte, []int) {
	return file_v1_kuadrant_proto_rawDescGZIP(), []int{1}
}

func (x *PongResponse) GetIn() *timestamp.Timestamp {
	if x != nil {
		return x.In
	}
	return nil
}

// evaluate the expression and whether or not to subscribe
type ResolveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Policy        *Policy                `protobuf:"bytes,1,opt,name=policy,proto3" json:"policy,omitempty"`
	Expression    string                 `protobuf:"bytes,2,opt,name=expression,proto3" json:"expression,omitempty"`
	Subscribe     bool                   `protobuf:"varint,3,opt,name=subscribe,proto3" json:"subscribe,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveRequest) Reset() {
	*x = ResolveRequest{}
	mi := &file_v1_kuadrant_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveRequest) ProtoMessage() {}

func (x *ResolveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_kuadrant_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveRequest.ProtoReflect.Descriptor instead.
func (*ResolveRequest) Descriptor() ([]byte, []int) {
	return file_v1_kuadrant_proto_rawDescGZIP(), []int{2}
}

func (x *ResolveRequest) GetPolicy() *Policy {
	if x != nil {
		return x.Policy
	}
	return nil
}

func (x *ResolveRequest) GetExpression() string {
	if x != nil {
		return x.Expression
	}
	return ""
}

func (x *ResolveRequest) GetSubscribe() bool {
	if x != nil {
		return x.Subscribe
	}
	return false
}

// Return the result as a cel value
type ResolveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CelResult     *v1alpha1.Value        `protobuf:"bytes,1,opt,name=cel_result,json=celResult,proto3" json:"cel_result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveResponse) Reset() {
	*x = ResolveResponse{}
	mi := &file_v1_kuadrant_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveResponse) ProtoMessage() {}

func (x *ResolveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_kuadrant_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveResponse.ProtoReflect.Descriptor instead.
func (*ResolveResponse) Descriptor() ([]byte, []int) {
	return file_v1_kuadrant_proto_rawDescGZIP(), []int{3}
}

func (x *ResolveResponse) GetCelResult() *v1alpha1.Value {
	if x != nil {
		return x.CelResult
	}
	return nil
}

type SubscribeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Event         *Event                 `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	Error         *status.Status         `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeResponse) Reset() {
	*x = SubscribeResponse{}
	mi := &file_v1_kuadrant_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeResponse) ProtoMessage() {}

func (x *SubscribeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_kuadrant_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeResponse.ProtoReflect.Descriptor instead.
func (*SubscribeResponse) Descriptor() ([]byte, []int) {
	return file_v1_kuadrant_proto_rawDescGZIP(), []int{4}
}

func (x *SubscribeResponse) GetEvent() *Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *SubscribeResponse) GetError() *status.Status {
	if x != nil {
		return x.Error
	}
	return nil
}

type SubscribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PolicyKind    string                 `protobuf:"bytes,1,opt,name=policy_kind,json=policyKind,proto3" json:"policy_kind,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	mi := &file_v1_kuadrant_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_kuadrant_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_v1_kuadrant_proto_rawDescGZIP(), []int{5}
}

func (x *SubscribeRequest) GetPolicyKind() string {
	if x != nil {
		return x.PolicyKind
	}
	return ""
}

type Event struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      *Metadata              `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_v1_kuadrant_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_v1_kuadrant_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_v1_kuadrant_proto_rawDescGZIP(), []int{6}
}

func (x *Event) GetMetadata() *Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type RegisterMutatorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Policy        *Policy                `protobuf:"bytes,1,opt,name=policy,proto3" json:"policy,omitempty"`
	Domain        Domain                 `protobuf:"varint,2,opt,name=domain,proto3,enum=kuadrant.v1.Domain" json:"domain,omitempty"`
	Binding       string                 `protobuf:"bytes,3,opt,name=binding,proto3" json:"binding,omitempty"`
	Expression    string                 `protobuf:"bytes,4,opt,name=expression,proto3" json:"expression,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterMutatorRequest) Reset() {
	*x = RegisterMutatorRequest{}
	mi := &file_v1_kuadrant_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterMutatorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterMutatorRequest) ProtoMessage() {}

func (x *RegisterMutatorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_kuadrant_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterMutatorRequest.ProtoReflect.Descriptor instead.
func (*RegisterMutatorRequest) Descriptor() ([]byte, []int) {
	return file_v1_kuadrant_proto_rawDescGZIP(), []int{7}
}

func (x *RegisterMutatorRequest) GetPolicy() *Policy {
	if x != nil {
		return x.Policy
	}
	return nil
}

func (x *RegisterMutatorRequest) GetDomain() Domain {
	if x != nil {
		return x.Domain
	}
	return Domain_DOMAIN_UNSPECIFIED
}

func (x *RegisterMutatorRequest) GetBinding() string {
	if x != nil {
		return x.Binding
	}
	return ""
}

func (x *RegisterMutatorRequest) GetExpression() string {
	if x != nil {
		return x.Expression
	}
	return ""
}

type ClearPolicyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Policy        *Policy                `protobuf:"bytes,1,opt,name=policy,proto3" json:"policy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClearPolicyRequest) Reset() {
	*x = ClearPolicyRequest{}
	mi := &file_v1_kuadrant_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClearPolicyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearPolicyRequest) ProtoMessage() {}

func (x *ClearPolicyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_kuadrant_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearPolicyRequest.ProtoReflect.Descriptor instead.
func (*ClearPolicyRequest) Descriptor() ([]byte, []int) {
	return file_v1_kuadrant_proto_rawDescGZIP(), []int{8}
}

func (x *ClearPolicyRequest) GetPolicy() *Policy {
	if x != nil {
		return x.Policy
	}
	return nil
}

type ClearPolicyResponse struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	ClearedSubscriptions int32                  `protobuf:"varint,1,opt,name=cleared_subscriptions,json=clearedSubscriptions,proto3" json:"cleared_subscriptions,omitempty"`
	ClearedMutators      int32                  `protobuf:"varint,2,opt,name=cleared_mutators,json=clearedMutators,proto3" json:"cleared_mutators,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ClearPolicyResponse) Reset() {
	*x = ClearPolicyResponse{}
	mi := &file_v1_kuadrant_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClearPolicyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearPolicyResponse) ProtoMessage() {}

func (x *ClearPolicyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_kuadrant_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearPolicyResponse.ProtoReflect.Descriptor instead.
func (*ClearPolicyResponse) Descriptor() ([]byte, []int) {
	return file_v1_kuadrant_proto_rawDescGZIP(), []int{9}
}

func (x *ClearPolicyResponse) GetClearedSubscriptions() int32 {
	if x != nil {
		return x.ClearedSubscriptions
	}
	return 0
}

func (x *ClearPolicyResponse) GetClearedMutators() int32 {
	if x != nil {
		return x.ClearedMutators
	}
	return 0
}

type RegisterActionMethodRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Policy          *Policy                `protobuf:"bytes,1,opt,name=policy,proto3" json:"policy,omitempty"`
	Url             string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`                                                // e.g. "grpc://my-service:8081"
	Service         string                 `protobuf:"bytes,3,opt,name=service,proto3" json:"service,omitempty"`                                        // gRPC service name
	Method          string                 `protobuf:"bytes,4,opt,name=method,proto3" json:"method,omitempty"`                                          // gRPC method name
	Name            string                 `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`                                              // Per-policy unique identifier for this action method
	MessageTemplate string                 `protobuf:"bytes,6,opt,name=message_template,json=messageTemplate,proto3" json:"message_template,omitempty"` // Opaque template string for building the gRPC request message
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RegisterActionMethodRequest) Reset() {
	*x = RegisterActionMethodRequest{}
	mi := &file_v1_kuadrant_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterActionMethodRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterActionMethodRequest) ProtoMessage() {}

func (x *RegisterActionMethodRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_kuadrant_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterActionMethodRequest.ProtoReflect.Descriptor instead.
func (*RegisterActionMethodRequest) Descriptor() ([]byte, []int) {
	return file_v1_kuadrant_proto_rawDescGZIP(), []int{10}
}

func (x *RegisterActionMethodRequest) GetPolicy() *Policy {
	if x != nil {
		return x.Policy
	}
	return nil
}

func (x *RegisterActionMethodRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *RegisterActionMethodRequest) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *RegisterActionMethodRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *RegisterActionMethodRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RegisterActionMethodRequest) GetMessageTemplate() string {
	if x != nil {
		return x.MessageTemplate
	}
	return ""
}

// RequestActionEntry represents a single action in the request phase.
type RequestActionEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActionType    ActionType             `protobuf:"varint,1,opt,name=action_type,json=actionType,proto3,enum=kuadrant.v1.ActionType" json:"action_type,omitempty"`
	Predicate     string                 `protobuf:"bytes,2,opt,name=predicate,proto3" json:"predicate,omitempty"` // CEL predicate — if false, skip this action
	Intention     string                 `protobuf:"bytes,3,opt,name=intention,proto3" json:"intention,omitempty"` // CEL expression evaluated against the gRPC response or request
	Method        string                 `protobuf:"bytes,4,opt,name=method,proto3" json:"method,omitempty"`       // Name of a registered ActionMethod (for grpc_method type)
	Var           string                 `protobuf:"bytes,5,opt,name=var,proto3" json:"var,omitempty"`             // Variable name for the gRPC response (used by onReply predicates)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestActionEntry) Reset() {
	*x = RequestActionEntry{}
	mi := &file_v1_kuadrant_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestActionEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestActionEntry) ProtoMessage() {}

func (x *RequestActionEntry) ProtoReflect() protoreflect.Message {
	mi := &file_v1_kuadrant_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestActionEntry.ProtoReflect.Descriptor instead.
func (*RequestActionEntry) Descriptor() ([]byte, []int) {
	return file_v1_kuadrant_proto_rawDescGZIP(), []int{11}
}

func (x *RequestActionEntry) GetActionType() ActionType {
	if x != nil {
		return x.ActionType
	}
	return ActionType_ACTION_TYPE_UNSPECIFIED
}

func (x *RequestActionEntry) GetPredicate() string {
	if x != nil {
		return x.Predicate
	}
	return ""
}

func (x *RequestActionEntry) GetIntention() string {
	if x != nil {
		return x.Intention
	}
	return ""
}

func (x *RequestActionEntry) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *RequestActionEntry) GetVar() string {
	if x != nil {
		return x.Var
	}
	return ""
}

// ResponseActionEntry represents a single action in the response phase.
type ResponseActionEntry struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ActionType      ActionType             `protobuf:"varint,1,opt,name=action_type,json=actionType,proto3,enum=kuadrant.v1.ActionType" json:"action_type,omitempty"`
	Predicate       string                 `protobuf:"bytes,2,opt,name=predicate,proto3" json:"predicate,omitempty"`                                       // CEL predicate — if false, skip this action
	HeadersToAdd    string                 `protobuf:"bytes,3,opt,name=headers_to_add,json=headersToAdd,proto3" json:"headers_to_add,omitempty"`           // CEL expression evaluating to a map of headers (for add_headers type)
	NewResponseCode int32                  `protobuf:"varint,4,opt,name=new_response_code,json=newResponseCode,proto3" json:"new_response_code,omitempty"` // HTTP status code (for with_response_code type)
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ResponseActionEntry) Reset() {
	*x = ResponseActionEntry{}
	mi := &file_v1_kuadrant_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseActionEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseActionEntry) ProtoMessage() {}

func (x *ResponseActionEntry) ProtoReflect() protoreflect.Message {
	mi := &file_v1_kuadrant_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseActionEntry.ProtoReflect.Descriptor instead.
func (*ResponseActionEntry) Descriptor() ([]byte, []int) {
	return file_v1_kuadrant_proto_rawDescGZIP(), []int{12}
}

func (x *ResponseActionEntry) GetActionType() ActionType {
	if x != nil {
		return x.ActionType
	}
	return ActionType_ACTION_TYPE_UNSPECIFIED
}

func (x *ResponseActionEntry) GetPredicate() string {
	if x != nil {
		return x.Predicate
	}
	return ""
}

func (x *ResponseActionEntry) GetHeadersToAdd() string {
	if x != nil {
		return x.HeadersToAdd
	}
	return ""
}

func (x *ResponseActionEntry) GetNewResponseCode() int32 {
	if x != nil {
		return x.NewResponseCode
	}
	return 0
}

// PipelineCommitRequest atomically replaces all pipeline actions for a policy.
type PipelineCommitRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Policy          *Policy                `protobuf:"bytes,1,opt,name=policy,proto3" json:"policy,omitempty"`
	RequestActions  []*RequestActionEntry  `protobuf:"bytes,2,rep,name=request_actions,json=requestActions,proto3" json:"request_actions,omitempty"`
	ResponseActions []*ResponseActionEntry `protobuf:"bytes,3,rep,name=response_actions,json=responseActions,proto3" json:"response_actions,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PipelineCommitRequest) Reset() {
	*x = PipelineCommitRequest{}
	mi := &file_v1_kuadrant_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PipelineCommitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PipelineCommitRequest) ProtoMessage() {}

func (x *PipelineCommitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_kuadrant_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PipelineCommitRequest.ProtoReflect.Descriptor instead.
func (*PipelineCommitRequest) Descriptor() ([]byte, []int) {
	return file_v1_kuadrant_proto_rawDescGZIP(), []int{13}
}

func (x *PipelineCommitRequest) GetPolicy() *Policy {
	if x != nil {
		return x.Policy
	}
	return nil
}

func (x *PipelineCommitRequest) GetRequestActions() []*RequestActionEntry {
	if x != nil {
		return x.RequestActions
	}
	return nil
}

func (x *PipelineCommitRequest) GetResponseActions() []*ResponseActionEntry {
	if x != nil {
		return x.ResponseActions
	}
	return nil
}

var File_v1_kuadrant_proto protoreflect.FileDescriptor

const file_v1_kuadrant_proto_rawDesc = "" +
	"\n" +
	"\x11v1/kuadrant.proto\x12\vkuadrant.v1\x1a\"v1/google/protobuf/timestamp.proto\x1a\x1ev1/google/protobuf/empty.proto\x1a'v1/google/api/expr/v1alpha1/value.proto\x1a\x1av1/google/rpc/status.proto\x1a\x0fv1/policy.proto\x1a\x0fv1/common.proto\";\n" +
	"\vPingRequest\x12,\n" +
	"\x03out\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x03out\":\n" +
	"\fPongResponse\x12*\n" +
	"\x02in\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x02in\"{\n" +
	"\x0eResolveRequest\x12+\n" +
	"\x06policy\x18\x01 \x01(\v2\x13.kuadrant.v1.PolicyR\x06policy\x12\x1e\n" +
	"\n" +
	"expression\x18\x02 \x01(\tR\n" +
	"expression\x12\x1c\n" +
	"\tsubscribe\x18\x03 \x01(\bR\tsubscribe\"Q\n" +
	"\x0fResolveResponse\x12>\n" +
	"\n" +
	"cel_result\x18\x01 \x01(\v2\x1f.google.api.expr.v1alpha1.ValueR\tcelResult\"g\n" +
	"\x11SubscribeResponse\x12(\n" +
	"\x05event\x18\x01 \x01(\v2\x12.kuadrant.v1.EventR\x05event\x12(\n" +
	"\x05error\x18\x02 \x01(\v2\x12.google.rpc.StatusR\x05error\"3\n" +
	"\x10SubscribeRequest\x12\x1f\n" +
	"\vpolicy_kind\x18\x01 \x01(\tR\n" +
	"policyKind\":\n" +
	"\x05Event\x121\n" +
	"\bmetadata\x18\x01 \x01(\v2\x15.kuadrant.v1.MetadataR\bmetadata\"\xac\x01\n" +
	"\x16RegisterMutatorRequest\x12+\n" +
	"\x06policy\x18\x01 \x01(\v2\x13.kuadrant.v1.PolicyR\x06policy\x12+\n" +
	"\x06domain\x18\x02 \x01(\x0e2\x13.kuadrant.v1.DomainR\x06domain\x12\x18\n" +
	"\abinding\x18\x03 \x01(\tR\abinding\x12\x1e\n" +
	"\n" +
	"expression\x18\x04 \x01(\tR\n" +
	"expression\"A\n" +
	"\x12ClearPolicyRequest\x12+\n" +
	"\x06policy\x18\x01 \x01(\v2\x13.kuadrant.v1.PolicyR\x06policy\"u\n" +
	"\x13ClearPolicyResponse\x123\n" +
	"\x15cleared_subscriptions\x18\x01 \x01(\x05R\x14clearedSubscriptions\x12)\n" +
	"\x10cleared_mutators\x18\x02 \x01(\x05R\x0fclearedMutators\"\xcd\x01\n" +
	"\x1bRegisterActionMethodRequest\x12+\n" +
	"\x06policy\x18\x01 \x01(\v2\x13.kuadrant.v1.PolicyR\x06policy\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12\x18\n" +
	"\aservice\x18\x03 \x01(\tR\aservice\x12\x16\n" +
	"\x06method\x18\x04 \x01(\tR\x06method\x12\x12\n" +
	"\x04name\x18\x05 \x01(\tR\x04name\x12)\n" +
	"\x10message_template\x18\x06 \x01(\tR\x0fmessageTemplate\"\xb4\x01\n" +
	"\x12RequestActionEntry\x128\n" +
	"\vaction_type\x18\x01 \x01(\x0e2\x17.kuadrant.v1.ActionTypeR\n" +
	"actionType\x12\x1c\n" +
	"\tpredicate\x18\x02 \x01(\tR\tpredicate\x12\x1c\n" +
	"\tintention\x18\x03 \x01(\tR\tintention\x12\x16\n" +
	"\x06method\x18\x04 \x01(\tR\x06method\x12\x10\n" +
	"\x03var\x18\x05 \x01(\tR\x03var\"\xbf\x01\n" +
	"\x13ResponseActionEntry\x128\n" +
	"\vaction_type\x18\x01 \x01(\x0e2\x17.kuadrant.v1.ActionTypeR\n" +
	"actionType\x12\x1c\n" +
	"\tpredicate\x18\x02 \x01(\tR\tpredicate\x12$\n" +
	"\x0eheaders_to_add\x18\x03 \x01(\tR\fheadersToAdd\x12*\n" +
	"\x11new_response_code\x18\x04 \x01(\x05R\x0fnewResponseCode\"\xdb\x01\n" +
	"\x15PipelineCommitRequest\x12+\n" +
	"\x06policy\x18\x01 \x01(\v2\x13.kuadrant.v1.PolicyR\x06policy\x12H\n" +
	"\x0frequest_actions\x18\x02 \x03(\v2\x1f.kuadrant.v1.RequestActionEntryR\x0erequestActions\x12K\n" +
	"\x10response_actions\x18\x03 \x03(\v2 .kuadrant.v1.ResponseActionEntryR\x0fresponseActions*E\n" +
	"\x06Domain\x12\x16\n" +
	"\x12DOMAIN_UNSPECIFIED\x10\x00\x12\x0f\n" +
	"\vDOMAIN_AUTH\x10\x01\x12\x12\n" +
	"\x0eDOMAIN_REQUEST\x10\x02*\x9e\x01\n" +
	"\n" +
	"ActionType\x12\x1b\n" +
	"\x17ACTION_TYPE_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17ACTION_TYPE_GRPC_METHOD\x10\x01\x12\x15\n" +
	"\x11ACTION_TYPE_ALLOW\x10\x02\x12\x1b\n" +
	"\x17ACTION_TYPE_ADD_HEADERS\x10\x03\x12\"\n" +
	"\x1eACTION_TYPE_WITH_RESPONSE_CODE\x10\x042\xbb\x04\n" +
	"\x10ExtensionService\x12=\n" +
	"\x04Ping\x12\x18.kuadrant.v1.PingRequest\x1a\x19.kuadrant.v1.PongResponse\"\x00\x12N\n" +
	"\tSubscribe\x12\x1d.kuadrant.v1.SubscribeRequest\x1a\x1e.kuadrant.v1.SubscribeResponse\"\x000\x01\x12F\n" +
	"\aResolve\x12\x1b.kuadrant.v1.ResolveRequest\x1a\x1c.kuadrant.v1.ResolveResponse\"\x00\x12P\n" +
	"\x0fRegisterMutator\x12#.kuadrant.v1.RegisterMutatorRequest\x1a\x16.google.protobuf.Empty\"\x00\x12R\n" +
	"\vClearPolicy\x12\x1f.kuadrant.v1.ClearPolicyRequest\x1a .kuadrant.v1.ClearPolicyResponse\"\x00\x12Z\n" +
	"\x14RegisterActionMethod\x12(.kuadrant.v1.RegisterActionMethodRequest\x1a\x16.google.protobuf.Empty\"\x00\x12N\n" +
	"\x0ePipelineCommit\x12\".kuadrant.v1.PipelineCommitRequest\x1a\x16.google.protobuf.Empty\"\x00B\x05Z\x03/v1b\x06proto3"

var (
	file_v1_kuadrant_proto_rawDescOnce sync.Once
	file_v1_kuadrant_proto_rawDescData []byte
)

func file_v1_kuadrant_proto_rawDescGZIP() []byte {
	file_v1_kuadrant_proto_rawDescOnce.Do(func() {
		file_v1_kuadrant_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_kuadrant_proto_rawDesc), len(file_v1_kuadrant_proto_rawDesc)))
	})
	return file_v1_kuadrant_proto_rawDescData
}

var file_v1_kuadrant_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_v1_kuadrant_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_v1_kuadrant_proto_goTypes = []any{
	(Domain)(0),                         // 0: kuadrant.v1.Domain
	(ActionType)(0),                     // 1: kuadrant.v1.ActionType
	(*PingRequest)(nil),                 // 2: kuadrant.v1.PingRequest
	(*PongResponse)(nil),                // 3: kuadrant.v1.PongResponse
	(*ResolveRequest)(nil),              // 4: kuadrant.v1.ResolveRequest
	(*ResolveResponse)(nil),             // 5: kuadrant.v1.ResolveResponse
	(*SubscribeResponse)(nil),           // 6: kuadrant.v1.SubscribeResponse
	(*SubscribeRequest)(nil),            // 7: kuadrant.v1.SubscribeRequest
	(*Event)(nil),                       // 8: kuadrant.v1.Event
	(*RegisterMutatorRequest)(nil),      // 9: kuadrant.v1.RegisterMutatorRequest
	(*ClearPolicyRequest)(nil),          // 10: kuadrant.v1.ClearPolicyRequest
	(*ClearPolicyResponse)(nil),         // 11: kuadrant.v1.ClearPolicyResponse
	(*RegisterActionMethodRequest)(nil), // 12: kuadrant.v1.RegisterActionMethodRequest
	(*RequestActionEntry)(nil),          // 13: kuadrant.v1.RequestActionEntry
	(*ResponseActionEntry)(nil),         // 14: kuadrant.v1.ResponseActionEntry
	(*PipelineCommitRequest)(nil),       // 15: kuadrant.v1.PipelineCommitRequest
	(*timestamp.Timestamp)(nil),         // 16: google.protobuf.Timestamp
	(*Policy)(nil),                      // 17: kuadrant.v1.Policy
	(*v1alpha1.Value)(nil),              // 18: google.api.expr.v1alpha1.Value
	(*status.Status)(nil),               // 19: google.rpc.Status
	(*Metadata)(nil),                    // 20: kuadrant.v1.Metadata
	(*empty.Empty)(nil),                 // 21: google.protobuf.Empty
}
var file_v1_kuadrant_proto_depIdxs = []int32{
	16, // 0: kuadrant.v1.PingRequest.out:type_name -> google.protobuf.Timestamp
	16, // 1: kuadrant.v1.PongResponse.in:type_name -> google.protobuf.Timestamp
	17, // 2: kuadrant.v1.ResolveRequest.policy:type_name -> kuadrant.v1.Policy
	18, // 3: kuadrant.v1.ResolveResponse.cel_result:type_name -> google.api.expr.v1alpha1.Value
	8,  // 4: kuadrant.v1.SubscribeResponse.event:type_name -> kuadrant.v1.Event
	19, // 5: kuadrant.v1.SubscribeResponse.error:type_name -> google.rpc.Status
	20, // 6: kuadrant.v1.Event.metadata:type_name -> kuadrant.v1.Metadata
	17, // 7: kuadrant.v1.RegisterMutatorRequest.policy:type_name -> kuadrant.v1.Policy
	0,  // 8: kuadrant.v1.RegisterMutatorRequest.domain:type_name -> kuadrant.v1.Domain
	17, // 9: kuadrant.v1.ClearPolicyRequest.policy:type_name -> kuadrant.v1.Policy
	17, // 10: kuadrant.v1.RegisterActionMethodRequest.policy:type_name -> kuadrant.v1.Policy
	1,  // 11: kuadrant.v1.RequestActionEntry.action_type:type_name -> kuadrant.v1.ActionType
	1,  // 12: kuadrant.v1.ResponseActionEntry.action_type:type_name -> kuadrant.v1.ActionType
	17, // 13: kuadrant.v1.PipelineCommitRequest.policy:type_name -> kuadrant.v1.Policy
	13, // 14: kuadrant.v1.PipelineCommitRequest.request_actions:type_name -> kuadrant.v1.RequestActionEntry
	14, // 15: kuadrant.v1.PipelineCommitRequest.response_actions:type_name -> kuadrant.v1.ResponseActionEntry
	2,  // 16: kuadrant.v1.ExtensionService.Ping:input_type -> kuadrant.v1.PingRequest
	7,  // 17: kuadrant.v1.ExtensionService.Subscribe:input_type -> kuadrant.v1.SubscribeRequest
	4,  // 18: kuadrant.v1.ExtensionService.Resolve:input_type -> kuadrant.v1.ResolveRequest
	9,  // 19: kuadrant.v1.ExtensionService.RegisterMutator:input_type -> kuadrant.v1.RegisterMutatorRequest
	10, // 20: kuadrant.v1.ExtensionService.ClearPolicy:input_type -> kuadrant.v1.ClearPolicyRequest
	12, // 21: kuadrant.v1.ExtensionService.RegisterActionMethod:input_type -> kuadrant.v1.RegisterActionMethodRequest
	15, // 22: kuadrant.v1.ExtensionService.PipelineCommit:input_type -> kuadrant.v1.PipelineCommitRequest
	3,  // 23: kuadrant.v1.ExtensionService.Ping:output_type -> kuadrant.v1.PongResponse
	6,  // 24: kuadrant.v1.ExtensionService.Subscribe:output_type -> kuadrant.v1.SubscribeResponse
	5,  // 25: kuadrant.v1.ExtensionService.Resolve:output_type -> kuadrant.v1.ResolveResponse
	21, // 26: kuadrant.v1.ExtensionService.RegisterMutator:output_type -> google.protobuf.Empty
	11, // 27: kuadrant.v1.ExtensionService.ClearPolicy:output_type -> kuadrant.v1.ClearPolicyResponse
	21, // 28: kuadrant.v1.ExtensionService.RegisterActionMethod:output_type -> google.protobuf.Empty
	21, // 29: kuadrant.v1.ExtensionService.PipelineCommit:output_type -> google.protobuf.Empty
	23, // [23:30] is the sub-list for method output_type
	16, // [16:23] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_v1_kuadrant_proto_init() }
func file_v1_kuadrant_proto_init() {
	if File_v1_kuadrant_proto != nil {
		return
	}
	file_v1_policy_proto_init()
	file_v1_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_kuadrant_proto_rawDesc), len(file_v1_kuadrant_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_kuadrant_proto_goTypes,
		DependencyIndexes: file_v1_kuadrant_proto_depIdxs,
		EnumInfos:         file_v1_kuadrant_proto_enumTypes,
		MessageInfos:      file_v1_kuadrant_proto_msgTypes,
	}.Build()
	File_v1_kuadrant_proto = out.File
	file_v1_kuadrant_proto_goTypes = nil
	file_v1_kuadrant_proto_depIdxs = nil
}
