// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: v1/plugin_config_service.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetPluginConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Gateway       string                 `protobuf:"bytes,1,opt,name=gateway,proto3" json:"gateway,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPluginConfigRequest) Reset() {
	*x = GetPluginConfigRequest{}
	mi := &file_v1_plugin_config_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPluginConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPluginConfigRequest) ProtoMessage() {}

func (x *GetPluginConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_plugin_config_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPluginConfigRequest.ProtoReflect.Descriptor instead.
func (*GetPluginConfigRequest) Descriptor() ([]byte, []int) {
	return file_v1_plugin_config_service_proto_rawDescGZIP(), []int{0}
}

func (x *GetPluginConfigRequest) GetGateway() string {
	if x != nil {
		return x.Gateway
	}
	return ""
}

type GetPluginConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConfigJson    []byte                 `protobuf:"bytes,1,opt,name=config_json,json=configJson,proto3" json:"config_json,omitempty"`
	Sha256        string                 `protobuf:"bytes,2,opt,name=sha256,proto3" json:"sha256,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPluginConfigResponse) Reset() {
	*x = GetPluginConfigResponse{}
	mi := &file_v1_plugin_config_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPluginConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPluginConfigResponse) ProtoMessage() {}

func (x *GetPluginConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_plugin_config_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPluginConfigResponse.ProtoReflect.Descriptor instead.
func (*GetPluginConfigResponse) Descriptor() ([]byte, []int) {
	return file_v1_plugin_config_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetPluginConfigResponse) GetConfigJson() []byte {
	if x != nil {
		return x.ConfigJson
	}
	return nil
}

func (x *GetPluginConfigResponse) GetSha256() string {
	if x != nil {
		return x.Sha256
	}
	return ""
}

var File_v1_plugin_config_service_proto protoreflect.FileDescriptor

const file_v1_plugin_config_service_proto_rawDesc = "" +
	"\n" +
	"\x1ev1/plugin_config_service.proto\x12\vkuadrant.v1\"2\n" +
	"\x16GetPluginConfigRequest\x12\x18\n" +
	"\agateway\x18\x01 \x01(\tR\agateway\"R\n" +
	"\x17GetPluginConfigResponse\x12\x1f\n" +
	"\vconfig_json\x18\x01 \x01(\fR\n" +
	"configJson\x12\x16\n" +
	"\x06sha256\x18\x02 \x01(\tR\x06sha2562u\n" +
	"\x13PluginConfigService\x12^\n" +
	"\x0fGetPluginConfig\x12#.kuadrant.v1.GetPluginConfigRequest\x1a$.kuadrant.v1.GetPluginConfigResponse\"\x00B\x05Z\x03/v1b\x06proto3"

var (
	file_v1_plugin_config_service_proto_rawDescOnce sync.Once
	file_v1_plugin_config_service_proto_rawDescData []byte
)

func file_v1_plugin_config_service_proto_rawDescGZIP() []byte {
	file_v1_plugin_config_service_proto_rawDescOnce.Do(func() {
		file_v1_plugin_config_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_plugin_config_service_proto_rawDesc), len(file_v1_plugin_config_service_proto_rawDesc)))
	})
	return file_v1_plugin_config_service_proto_rawDescData
}

var file_v1_plugin_config_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_v1_plugin_config_service_proto_goTypes = []any{
	(*GetPluginConfigRequest)(nil),  // 0: kuadrant.v1.GetPluginConfigRequest
	(*GetPluginConfigResponse)(nil), // 1: kuadrant.v1.GetPluginConfigResponse
}
var file_v1_plugin_config_service_proto_depIdxs = []int32{
	0, // 0: kuadrant.v1.PluginConfigService.GetPluginConfig:input_type -> kuadrant.v1.GetPluginConfigRequest
	1, // 1: kuadrant.v1.PluginConfigService.GetPluginConfig:output_type -> kuadrant.v1.GetPluginConfigResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_v1_plugin_config_service_proto_init() }
func file_v1_plugin_config_service_proto_init() {
	if File_v1_plugin_config_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_plugin_config_service_proto_rawDesc), len(file_v1_plugin_config_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_plugin_config_service_proto_goTypes,
		DependencyIndexes: file_v1_plugin_config_service_proto_depIdxs,
		MessageInfos:      file_v1_plugin_config_service_proto_msgTypes,
	}.Build()
	File_v1_plugin_config_service_proto = out.File
	file_v1_plugin_config_service_proto_goTypes = nil
	file_v1_plugin_config_service_proto_depIdxs = nil
}
