// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: v1/plugin_config_service.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PluginConfigService_GetPluginConfig_FullMethodName = "/kuadrant.v1.PluginConfigService/GetPluginConfig"
)

// PluginConfigServiceClient is the client API for PluginConfigService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// PluginConfigService allows wasm components to fetch the full wasm plugin
// configuration (ActionSets) for a gateway, instead of having it embedded
// inline in the EnvoyFilter/WasmPlugin resource.
type PluginConfigServiceClient interface {
	GetPluginConfig(ctx context.Context, in *GetPluginConfigRequest, opts ...grpc.CallOption) (*GetPluginConfigResponse, error)
}

type pluginConfigServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPluginConfigServiceClient(cc grpc.ClientConnInterface) PluginConfigServiceClient {
	return &pluginConfigServiceClient{cc}
}

func (c *pluginConfigServiceClient) GetPluginConfig(ctx context.Context, in *GetPluginConfigRequest, opts ...grpc.CallOption) (*GetPluginConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPluginConfigResponse)
	err := c.cc.Invoke(ctx, PluginConfigService_GetPluginConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PluginConfigServiceServer is the server API for PluginConfigService service.
// All implementations must embed UnimplementedPluginConfigServiceServer
// for forward compatibility.
//
// PluginConfigService allows wasm components to fetch the full wasm plugin
// configuration (ActionSets) for a gateway, instead of having it embedded
// inline in the EnvoyFilter/WasmPlugin resource.
type PluginConfigServiceServer interface {
	GetPluginConfig(context.Context, *GetPluginConfigRequest) (*GetPluginConfigResponse, error)
	mustEmbedUnimplementedPluginConfigServiceServer()
}

// UnimplementedPluginConfigServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPluginConfigServiceServer struct{}

func (UnimplementedPluginConfigServiceServer) GetPluginConfig(context.Context, *GetPluginConfigRequest) (*GetPluginConfigResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPluginConfig not implemented")
}
func (UnimplementedPluginConfigServiceServer) mustEmbedUnimplementedPluginConfigServiceServer() {}
func (UnimplementedPluginConfigServiceServer) testEmbeddedByValue()                             {}

// UnsafePluginConfigServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PluginConfigServiceServer will
// result in compilation errors.
type UnsafePluginConfigServiceServer interface {
	mustEmbedUnimplementedPluginConfigServiceServer()
}

func RegisterPluginConfigServiceServer(s grpc.ServiceRegistrar, srv PluginConfigServiceServer) {
	// If the following call panics, it indicates UnimplementedPluginConfigServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PluginConfigService_ServiceDesc, srv)
}

func _PluginConfigService_GetPluginConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPluginConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginConfigServiceServer).GetPluginConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginConfigService_GetPluginConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginConfigServiceServer).GetPluginConfig(ctx, req.(*GetPluginConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PluginConfigService_ServiceDesc is the grpc.ServiceDesc for PluginConfigService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PluginConfigService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "kuadrant.v1.PluginConfigService",
	HandlerType: (*PluginConfigServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPluginConfig",
			Handler:    _PluginConfigService_GetPluginConfig_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "v1/plugin_config_service.proto",
}
