// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.19.6
// source: v1/policy.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Policy struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      *Metadata              `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	TargetRefs    []*TargetRef           `protobuf:"bytes,2,rep,name=targetRefs,proto3" json:"targetRefs,omitempty"`
	Status        *PolicyStatus          `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Policy) Reset() {
	*x = Policy{}
	mi := &file_v1_policy_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Policy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Policy) ProtoMessage() {}

func (x *Policy) ProtoReflect() protoreflect.Message {
	mi := &file_v1_policy_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Policy.ProtoReflect.Descriptor instead.
func (*Policy) Descriptor() ([]byte, []int) {
	return file_v1_policy_proto_rawDescGZIP(), []int{0}
}

func (x *Policy) GetMetadata() *Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Policy) GetTargetRefs() []*TargetRef {
	if x != nil {
		return x.TargetRefs
	}
	return nil
}

func (x *Policy) GetStatus() *PolicyStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

type PolicyStatus struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	ObservedGeneration int64                  `protobuf:"varint,1,opt,name=observedGeneration,proto3" json:"observedGeneration,omitempty"`
	Conditions         []*Condition           `protobuf:"bytes,2,rep,name=conditions,proto3" json:"conditions,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *PolicyStatus) Reset() {
	*x = PolicyStatus{}
	mi := &file_v1_policy_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PolicyStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PolicyStatus) ProtoMessage() {}

func (x *PolicyStatus) ProtoReflect() protoreflect.Message {
	mi := &file_v1_policy_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PolicyStatus.ProtoReflect.Descriptor instead.
func (*PolicyStatus) Descriptor() ([]byte, []int) {
	return file_v1_policy_proto_rawDescGZIP(), []int{1}
}

func (x *PolicyStatus) GetObservedGeneration() int64 {
	if x != nil {
		return x.ObservedGeneration
	}
	return 0
}

func (x *PolicyStatus) GetConditions() []*Condition {
	if x != nil {
		return x.Conditions
	}
	return nil
}

var File_v1_policy_proto protoreflect.FileDescriptor

const file_v1_policy_proto_rawDesc = "" +
	"\n" +
	"\x0fv1/policy.proto\x12\vkuadrant.v1\x1a\x0fv1/common.proto\"\xa6\x01\n" +
	"\x06Policy\x121\n" +
	"\bmetadata\x18\x01 \x01(\v2\x15.kuadrant.v1.MetadataR\bmetadata\x126\n" +
	"\n" +
	"targetRefs\x18\x02 \x03(\v2\x16.kuadrant.v1.TargetRefR\n" +
	"targetRefs\x121\n" +
	"\x06status\x18\x03 \x01(\v2\x19.kuadrant.v1.PolicyStatusR\x06status\"v\n" +
	"\fPolicyStatus\x12.\n" +
	"\x12observedGeneration\x18\x01 \x01(\x03R\x12observedGeneration\x126\n" +
	"\n" +
	"conditions\x18\x02 \x03(\v2\x16.kuadrant.v1.ConditionR\n" +
	"conditionsB\x05Z\x03/v1b\x06proto3"

var (
	file_v1_policy_proto_rawDescOnce sync.Once
	file_v1_policy_proto_rawDescData []byte
)

func file_v1_policy_proto_rawDescGZIP() []byte {
	file_v1_policy_proto_rawDescOnce.Do(func() {
		file_v1_policy_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_policy_proto_rawDesc), len(file_v1_policy_proto_rawDesc)))
	})
	return file_v1_policy_proto_rawDescData
}

var file_v1_policy_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_v1_policy_proto_goTypes = []any{
	(*Policy)(nil),       // 0: kuadrant.v1.Policy
	(*PolicyStatus)(nil), // 1: kuadrant.v1.PolicyStatus
	(*Metadata)(nil),     // 2: kuadrant.v1.Metadata
	(*TargetRef)(nil),    // 3: kuadrant.v1.TargetRef
	(*Condition)(nil),    // 4: kuadrant.v1.Condition
}
var file_v1_policy_proto_depIdxs = []int32{
	2, // 0: kuadrant.v1.Policy.metadata:type_name -> kuadrant.v1.Metadata
	3, // 1: kuadrant.v1.Policy.targetRefs:type_name -> kuadrant.v1.TargetRef
	1, // 2: kuadrant.v1.Policy.status:type_name -> kuadrant.v1.PolicyStatus
	4, // 3: kuadrant.v1.PolicyStatus.conditions:type_name -> kuadrant.v1.Condition
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_v1_policy_proto_init() }
func file_v1_policy_proto_init() {
	if File_v1_policy_proto != nil {
		return
	}
	file_v1_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_policy_proto_rawDesc), len(file_v1_policy_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v1_policy_proto_goTypes,
		DependencyIndexes: file_v1_policy_proto_depIdxs,
		MessageInfos:      file_v1_policy_proto_msgTypes,
	}.Build()
	File_v1_policy_proto = out.File
	file_v1_policy_proto_goTypes = nil
	file_v1_policy_proto_depIdxs = nil
}
