package kuadrantcontrollermanifests

import (
	"embed"

	logf "sigs.k8s.io/controller-runtime/pkg/log"
)

// Content holds kuadrant manifests
//go:embed autogenerated
var content embed.FS

func Content() ([]byte, error) {
	logf.Log.V(1).Info("Resource file", "name", "autogenerated/kuadrant-controller.yaml")
	return content.ReadFile("autogenerated/kuadrant-controller.yaml")
}
