apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "authorino-operator.fullname" . }}
  labels:
    {{- include "authorino-operator.labels" . | nindent 4 }}
spec:
  {{- if .Values.replicas }}
  replicas: {{ .Values.replicas }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "authorino-operator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "authorino-operator.selectorLabels" . | nindent 8 }}
    spec:
      securityContext:
        runAsNonRoot: true
      serviceAccountName: {{ include "authorino-operator.serviceAccountName" . }}
      terminationGracePeriodSeconds: 10
      containers:
      - name: manager
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command:
        - /manager
        args:
        - --leader-elect
        {{- if .Values.authorinoImage }}
        env:
        - name: RELATED_IMAGE_AUTHORINO
          value: {{ .Values.authorinoImage }}
        {{- end }}
        ports:
        - name: metrics
          containerPort: 8080
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
          seccompProfile:
            type: RuntimeDefault
        {{- with .Values.resources }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}
