apiVersion: v1
kind: ServiceAccount
metadata:
  name: authorino-operator
  namespace: '{{ .Release.Namespace }}'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: authorino-operator-leader-election
  namespace: '{{ .Release.Namespace }}'
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: authorino-operator-leader-election
  namespace: '{{ .Release.Namespace }}'
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: authorino-operator-leader-election
subjects:
  - kind: ServiceAccount
    name: authorino-operator
    namespace: '{{ .Release.Namespace }}'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: authorino-operator-manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: authorino-operator-manager
subjects:
  - kind: ServiceAccount
    name: authorino-operator
    namespace: '{{ .Release.Namespace }}'
---
apiVersion: v1
data:
  controller_manager_config.yaml: |
    apiVersion: controller-runtime.sigs.k8s.io/v1alpha1
    kind: ControllerManagerConfig
    health:
      healthProbeBindAddress: :8081
    metrics:
      bindAddress: 127.0.0.1:8080
    webhook:
      port: 9443
    leaderElection:
      leaderElect: true
      resourceName: aac3a15d.authorino.kuadrant.io
kind: ConfigMap
metadata:
  name: manager-config
  namespace: '{{ .Release.Namespace }}'
---
apiVersion: v1
kind: Service
metadata:
  labels:
    control-plane: authorino-operator
  name: authorino-operator-metrics
  namespace: '{{ .Release.Namespace }}'
spec:
  ports:
    - name: metrics
      port: 8080
      targetPort: metrics
  selector:
    control-plane: authorino-operator
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    control-plane: authorino-operator
  name: authorino-operator
  namespace: '{{ .Release.Namespace }}'
spec:
  replicas: 1
  selector:
    matchLabels:
      control-plane: authorino-operator
  template:
    metadata:
      labels:
        control-plane: authorino-operator
    spec:
      containers:
        - args:
            - --leader-elect
          command:
            - /manager
          env:
            - name: RELATED_IMAGE_AUTHORINO
              value: quay.io/kuadrant/authorino:latest
          image: quay.io/kuadrant/authorino-operator:latest
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 20
          name: manager
          ports:
            - containerPort: 8080
              name: metrics
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            limits:
              cpu: 200m
              memory: 300Mi
            requests:
              cpu: 200m
              memory: 200Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
            seccompProfile:
              type: RuntimeDefault
      securityContext:
        runAsNonRoot: true
      serviceAccountName: authorino-operator
      terminationGracePeriodSeconds: 10
