{{- if .Values.rbac.install }}
---
# Authorino Operator ClusterRole
{{ .Files.Get "static/rbac/authorino_operator_role.yaml" }}
---
# Authorino Workload ClusterRole
{{ .Files.Get "static/rbac/authorino_workload_role.yaml" }}
---
# Authorino K8s Auth ClusterRole
{{ .Files.Get "static/rbac/k8s_auth_role.yaml" }}
{{- end }}
