# permissions for end users to view oidcpolicies.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: kuadrant-operator
    app.kubernetes.io/managed-by: kustomize
  name: oidcpolicy-viewer-role
rules:
- apiGroups:
  - kuadrant.io
  resources:
  - oidcpolicies
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kuadrant.io
  resources:
  - oidcpolicies/status
  verbs:
  - get
