apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kuadrant-pull-secret-reader
  namespace: openshift-config
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  resourceNames:
  - pull-secret
  - additional-pull-secret
  verbs:
  - get
