apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kuadrant-pull-secret-reader
  namespace: openshift-config
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kuadrant-pull-secret-reader
subjects:
- kind: ServiceAccount
  name: controller-manager
  namespace: system
