# permissions for end users to view planpolicies.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: planpolicy-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: kuadrant-operator
    app.kubernetes.io/part-of: kuadrant-operator
    app.kubernetes.io/managed-by: kustomize
  name: planpolicy-viewer-role
rules:
- apiGroups:
  - kuadrant.io
  resources:
  - planpolicies
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kuadrant.io
  resources:
  - planpolicies/status
  verbs:
  - get
