# permissions for end users to view ratelimitpolicies.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ratelimitpolicy-viewer-role
rules:
- apiGroups:
  - apim.kuadrant.io
  resources:
  - ratelimitpolicies
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apim.kuadrant.io
  resources:
  - ratelimitpolicies/status
  verbs:
  - get
