# permissions for end users to edit ratelimitpolicies.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ratelimitpolicy-editor-role
rules:
- apiGroups:
  - apim.kuadrant.io
  resources:
  - ratelimitpolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apim.kuadrant.io
  resources:
  - ratelimitpolicies/status
  verbs:
  - get
