---
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: istiocontrolplane
spec:
  profile: default
  namespace: istio-system
  components:
    base:
      enabled: true
    cni:
      enabled: false
    egressGateways:
      - enabled: false
        name: istio-egressgateway
    ingressGateways:
      - enabled: true
        name: istio-ingressgateway
        k8s:
          service:
            type: NodePort
            ports:
              - name: status-port
                port: 15021
                protocol: TCP
                targetPort: 15021
              - name: http2
                port: 80
                protocol: TCP
                targetPort: 8080
                nodePort: 30950
              - name: https
                port: 443
                protocol: TCP
                targetPort: 8443
                nodePort: 30951
          resources:
            requests:
              cpu: "0"
    pilot:
      enabled: true
      k8s:
        resources:
          requests:
            cpu: "0"
  values:
    pilot:
      autoscaleEnabled: false
    gateways:
      istio-ingressgateway:
        type: ClusterIP
        autoscaleEnabled: false
    global:
      istioNamespace: istio-system
