---
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: istiocontrolplane
spec:
  profile: default
  namespace: istio-system
  components:
    base:
      enabled: true
    cni:
      enabled: false
    egressGateways:
      - enabled: false
        name: istio-egressgateway
    ingressGateways:
      - enabled: false
        name: istio-ingressgateway
    pilot:
      enabled: true
      k8s:
        env:
        - name: PILOT_ENABLE_ALPHA_GATEWAY_API
          value: "true"
        resources:
          requests:
            cpu: "0"
  values:
    pilot:
      autoscaleEnabled: false
    global:
      istioNamespace: istio-system
