apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: my-route-${DNSPOLICY_NAMESPACE}
spec:
  parentRefs:
    - kind: Gateway
      name: prod-web-istio
      namespace: ${DNSPOLICY_NAMESPACE}
  hostnames:
    - "app.${KUADRANT_ZONE_ROOT_DOMAIN}"
  rules:
    - backendRefs:
        - name: echo
          port: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: echo
spec:
  ports:
    - name: http-port
      port: 8080
      targetPort: http-port
      protocol: TCP
  selector:
    app: echo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: echo
  template:
    metadata:
      labels:
        app: echo
    spec:
      containers:
        - name: echo
          image: mirror.gcr.io/jmalloc/echo-server
          ports:
            - name: http-port
              containerPort: 8080
              protocol: TCP
