apiVersion: kuadrant.io/v1alpha1
kind: DNSPolicy
metadata:
  name: prod-web
  namespace: gateway
spec:
  targetRef:
    name: prod-web-istio
    group: gateway.networking.k8s.io
    kind: Gateway
  routingStrategy: loadbalanced
  healthCheck:
    endpoint: "/"
    port: 443
    protocol: "HTTPS"
    failureThreshold: 5