---
apiVersion: apim.kuadrant.io/v1alpha1
kind: AuthPolicy
metadata:
  name: toystore
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: toystore
  rules:
  - hosts: ["*.toystore.com"]
    methods: ["DELETE", "POST"]
    paths: ["/admin*"]
  authSchemes:
  - hosts: ["api.toystore.com"]
    identity:
    - name: apikey
      apiKey:
        labelSelectors:
          app: toystore
      credentials:
        in: authorization_header
        keySelector: APIKEY
    response:
    - json:
        properties:
          - name: user-id
            value: null
            valueFrom:
              authJSON: auth.identity.metadata.annotations.secret\.kuadrant\.io/user-id
      name: rate-limit-apikey
      wrapper: envoyDynamicMetadata
      wrapperKey: ext_auth_data
---
apiVersion: apim.kuadrant.io/v1alpha1
kind: AuthPolicy
metadata:
  name: toystore
  namespace: kuadrant-system
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: Gateway
    name: kuadrant-gwapi-gateway
  rules:
  - hosts: ["*.toystore.com"]
  authSchemes:
  - hosts: ["api.toystore.com"]
    identity:
      - name: apikey
        apiKey:
          labelSelectors:
            app: toystore
            admin: "yes"
        credentials:
          in: authorization_header
          keySelector: APIKEY
