---
apiVersion: apim.kuadrant.io/v1alpha1
kind: AuthPolicy
metadata:
  name: toystore
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: toystore
  rules:
  - hosts: ["*.toystore.com"]
    methods: ["DELETE", "POST"]
    paths: ["/admin*"]
  authSchemes:
  - hosts: ["api.toystore.com"]
    identity:
    - name: friends
      apiKey:
        labelSelectors:
          group: friends
      credentials:
        in: authorization_header
        keySelector: APIKEY
