---
apiVersion: kuadrant.io/v1beta2
kind: AuthPolicy
metadata:
  name: toystore
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: toystore
  routes: # TODO(@guicassolato): replace for routeSelectors when available
  - methods:
    - DELETE
    - POST
    paths:
    - "/admin*"
  rules:
    authentication:
      "apikey":
        apiKey:
          selector:
            matchLabels:
              app: toystore
      credentials:
        in: authorization_header
        keySelector: APIKEY
    response:
      success:
        dynamicMetadata:
          "ext_auth_data":
            json:
              properties:
                "user-id":
                  selector: auth.identity.metadata.annotations.secret\.kuadrant\.io/user-id
---
apiVersion: kuadrant.io/v1beta1
kind: AuthPolicy
metadata:
  name: toystore
  namespace: istio-system
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: Gateway
    name: istio-ingressgateway
  routes: # TODO(@guicassolato): replace with routeSelectors when available
  - hosts:
    - "*.toystore.com"
  rules:
    authentication:
      "apikey":
        apiKey:
          selector:
            matchLabels:
              app: toystore
              admin: "yes"
        credentials:
          authorizationHeader:
            prefix: APIKEY
