apiVersion: kuadrant.io/v1beta2
kind: RateLimitPolicy
metadata:
  name: toystore-httproute
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: toystore
  limits:
    "global":
      rates:
      - limit: 6
        duration: 30
        unit: second

    "get-toy":
      rates:
      - limit: 5
        duration: 30
        unit: second
      routeSelectors:
      - matches:
        - path:
            type: Exact
            value: "/toy"
          method: GET

    "admin-post-or-delete-toy-per-user":
      rates:
      - limit: 2
        duration: 30
        unit: second
      counters:
      - metadata.filter_metadata.envoy\.filters\.http\.ext_authz.username
      routeSelectors:
      - matches:
        - path:
            type: Exact
            value: "/admin/toy"
          method: POST
      - matches:
        - path:
            type: Exact
            value: "/admin/toy"
          method: DELETE
      when:
      - selector: metadata.filter_metadata.envoy\.filters\.http\.ext_authz.admin
        operator: eq
        value: "true"
