---
apiVersion: kuadrant.io/v1beta1
kind: RateLimitPolicy
metadata:
  name: toystore-httproute
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: toystore
  rateLimits:
    - rules:
      - paths: ["/toy"]
        methods: ["GET"]
      configurations:
        - actions:
            - generic_key:
                descriptor_key: get_toy
                descriptor_value: "yes"
      limits:
        - conditions: ["get_toy == 'yes'"]
          maxValue: 2
          seconds: 30
          variables: []
    - rules:
      - paths: ["/admin/toy"]
        methods: ["POST", "DELETE"]
      configurations:
        - actions:
            - generic_key:
                descriptor_key: admin
                descriptor_value: "yes"
            - metadata:
                descriptor_key: "user_id"
                default_value: "no-user"
                metadata_key:
                  key: "envoy.filters.http.ext_authz"
                  path:
                    - segment:
                        key: "ext_auth_data"
                    - segment:
                        key: "user_id"
      limits:
        - conditions:
            - "admin == 'yes'"
            - "user_id == 'bob'"
          maxValue: 2
          seconds: 30
          variables: []
        - conditions:
            - "admin == 'yes'"
            - "user_id == 'alice'"
          maxValue: 4
          seconds: 30
          variables: []
    - configurations:
        - actions:
            - generic_key:
                descriptor_key: vhaction
                descriptor_value: "yes"
      limits:
        - conditions: ["vhaction == 'yes'"]
          maxValue: 6
          seconds: 30
          variables: []
