apiVersion: kuadrant.io/v1
kind: RateLimitPolicy
metadata:
  name: toystore-gw
  namespace: gateway-system
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: Gateway
    name: kuadrant-ingressgateway
  limits:
    "expensive-operation":
      rates:
      - limit: 2
        window: 30s
      when:
      - predicate: "request.method == 'POST'"

    "limit-per-ip":
      rates:
      - limit: 5
        window: 30s
      when:
      - predicate: "source.id == source.address"
