{
 "title": "DNS Operator overview",
 "tags": [ "kuadrant" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Health Check Probes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Number of active probes",
   "type": "gauge",
   "gridPos": { "h": 16, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kuadrant_dnshealthcheckprobe_healthy_status == 1)",
     "legendFormat": "healthy"
    },
    {
     "expr": "count(kuadrant_dnshealthcheckprobe_healthy_status != 1) or vector(0)",
     "legendFormat": "unhealthy"
    },
    {
     "expr": "count(kuadrant_dnshealthcheckprobe_healthy_status)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Probe request rate by response code (req/s)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 21, "x": 3, "y": 1 },
   "targets": [
    {
     "expr": "sum by (client, code) (rate(http_client_requests_total{client=\"probe\"}[15m]))",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "Probe latency (seconds)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 21, "x": 3, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(http_client_request_latency_seconds_bucket{client=\"probe\",code=\"200\"}[15m])))",
     "legendFormat": "99%ile"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(http_client_request_latency_seconds_bucket{client=\"probe\",code=\"200\"}[15m])))",
     "legendFormat": "95%ile"
    }
   ]
  },
  { "title": "DNS Provider", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Provider latency (seconds)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le, client) (rate(http_client_request_latency_seconds_bucket{client=~\"aws|google|azure\",code=\"200\"}[15m])))",
     "legendFormat": "{{client}}:99%ile"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le, client) (rate(http_client_request_latency_seconds_bucket{client=~\"aws|google|azure\",code=\"200\"}[15m])))",
     "legendFormat": "{{client}}:95%ile"
    }
   ]
  },
  {
   "title": "Provider request rate by response code (req/s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "sum by (client, code) (rate(http_client_requests_total{client=~\"aws|google|azure\"}[15m]))",
     "legendFormat": "{{client}}:{{code}}"
    }
   ]
  },
  { "title": "Delegated Records", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Secondary Cluster Pre Primary",
   "type": "stat",
   "description": "Number of secondary cluster each primary are configured to listen too. Count should be the sum of primary and secondary cluster - 1.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dns_provider_active_multi_cluster_count",
     "legendFormat": "{{cluster_id}}"
    }
   ]
  },
  {
   "title": "Authoritative Record Sync",
   "type": "timeseries",
   "description": "When authoritative records across the multi cluster are in sync the value should be one. Any value greater mean the clusters are out of sync.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "targets": [
    {
     "expr": "count by (dns_record_name, dns_record_namespace)(group by (dns_record_name, dns_record_namespace, sha) (dns_provider_authoritative_record_spec_info))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Delegated Records",
   "type": "stat",
   "description": "Gives the total count of the number of delegated records within the system.",
   "gridPos": { "h": 10, "w": 5, "x": 0, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(max by (cluster_id) (dns_provider_remote_records))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Remote Record Reconcile Count",
   "type": "timeseries",
   "description": "Gives information on how many times a delegated record has been reconcile by a primary cluster.",
   "gridPos": { "h": 10, "w": 19, "x": 5, "y": 35 },
   "targets": [
    {
     "expr": "dns_provider_remote_record_reconcile_count",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}