{
 "title": "phils",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "DNS Provider latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(histogram_quantile(0.99, rate(http_client_request_latency_seconds_bucket{client=~\"aws|gcp|azure\"}[15m]))) by (client, method)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of active probes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by () (dns_health_probe_counter)",
     "legendFormat": "__auto"
    },
    { "expr": "state", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Requests to DNS Provider",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by (client, code, method) (delta(http_client_requests_total{client=~\"aws|gcp|azure\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of requests made by health check probes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum by (client, code) (delta(http_client_requests_total{client=\"probe\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DNS Probe Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sum(histogram_quantile(0.99, rate(http_client_request_latency_seconds_bucket{client=~\"probe\"}[10m]))) by (client, method)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}