---
- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/rateLimits/items/properties/configurations/items/properties/actions/items/oneOf
  value:
    - required: ["generic_key"]
    - required: ["metadata"]
    - required: ["remote_address"]
    - required: ["request_headers"]
