---
apiVersion: kuadrant.io/v1beta1
kind: AuthPolicy
metadata:
  name: toystore
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: toystore
  rules:
  authScheme:
    identity:
      - name: friends
        apiKey:
          allNamespaces: true
          selector:
            matchLabels:
              app: toystore
        credentials:
          in: authorization_header
          keySelector: APIKEY
    response:
      - json:
          properties:
            - name: userID
              valueFrom:
                authJSON: auth.identity.metadata.annotations.secret\.kuadrant\.io/user-id
        name: rate-limit-apikey
        wrapper: envoyDynamicMetadata
        wrapperKey: ext_auth_data
