apiVersion: kuadrant.io/v1alpha1
kind: PlanPolicy
metadata:
  labels:
    app.kubernetes.io/name: planpolicy
    app.kubernetes.io/instance: planpolicy-sample
    app.kubernetes.io/part-of: kuadrant-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: kuadrant-operator
  name: planpolicy-sample
spec: {}
