---
apiVersion: kuadrant.io/v1alpha1
kind: TLSPolicy
metadata:
  name: tlspolicy-sample
spec:
  targetRef:
    name: example-gateway
    group: gateway.networking.k8s.io
    kind: Gateway
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: self-signed-ca
