## Append samples you want in your CSV to this file as resources ##
resources:
- kuadrant_v1beta1_kuadrant.yaml
- kuadrant_v1beta3_authpolicy.yaml
- kuadrant_v1beta3_ratelimitpolicy.yaml
- kuadrant_v1alpha1_dnspolicy.yaml
- kuadrant_v1alpha1_tlspolicy.yaml
#+kubebuilder:scaffold:manifestskustomizesamples
