apiVersion: networking.kuadrant.io/v1beta1
kind: APIProduct
metadata:
  name: animaltoys
spec:
  hosts:
    - api.animaltoys.127.0.0.1.nip.io
  APIs:
    - name: dogs
      namespace: default
      tag: production
      mapping:
        prefix: /dogs
    - name: cats
      namespace: default
      tag: production
      mapping:
        prefix: /cats
  securityScheme:
    - name: MyAPIKey
      apiKeyAuth:
        location: authorization_header
        name: APIKEY
        credential_source:
          labelSelectors:
            secret.kuadrant.io/managed-by: authorino
            api: animaltoys
  rateLimit:
    global:
      maxValue: 100
      period: 30
    perRemoteIP:
      maxValue: 10
      period: 30
    authenticated:
      maxValue: 5
      period: 30
