apiVersion: v1
kind: Service
metadata:
  name: {{ include "limitador.fullname" . }}
  labels:
    {{- include "limitador.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.http.type }}
  ports:
  - name: http
    port: {{ .Values.service.http.port }}
    targetPort: http
    protocol: TCP
  - name: grpc
    port: {{ .Values.service.grpc.port }}
    targetPort: grpc
    protocol: TCP
  selector:
    {{- include "limitador.selectorLabels" . | nindent 4 }}
