---
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  image: kindest/node:v1.27.3
  extraPortMappings:
    - containerPort: 30950
      hostPort: 9080
    - containerPort: 30951
      hostPort: 9443
    - containerPort: 80
      hostPort: 9081
      protocol: TCP
    - containerPort: 443
      hostPort: 9444
      protocol: TCP
