apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - istio-tracing.yaml

patches:
  - path: istio-patch.yaml
    target:
      group: sailoperator.io
      version: v1
      kind: Istio
      name: default
