resources:
- github.com/Kuadrant/multicluster-gateway-controller/config/policy-controller/default?ref=main

patchesStrategicMerge:
- delete-ns.yaml

patches:
- patch: |-
    - op: add
      path: /spec/template/spec/containers/0/args/-
      value: --ocm-hub=false
  target:
    kind: Deployment
