# Rate limit policy to protect an API
# Each user ID is entitled to a limit of 5 requests to the API every 10 seconds.
apiVersion: kuadrant.io/v1beta1
kind: RateLimitPolicy
metadata:
  name: toystore-rate-limit
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: toystore
  rateLimits:
    - configurations:
        - actions:
            - metadata:
                descriptor_key: "userID"
                default_value: "no-user"
                metadata_key:
                  key: "envoy.filters.http.ext_authz"
                  path:
                    - segment:
                        key: "ext_auth_data"
                    - segment:
                        key: "userID"
      limits:
        - conditions: []
          maxValue: 5
          seconds: 10
          variables:
            - userID
