// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: gateway_api.proto

package v0

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Policy struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      *Metadata              `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	TargetRefs    []*TargetRef           `protobuf:"bytes,2,rep,name=targetRefs,proto3" json:"targetRefs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Policy) Reset() {
	*x = Policy{}
	mi := &file_gateway_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Policy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Policy) ProtoMessage() {}

func (x *Policy) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Policy.ProtoReflect.Descriptor instead.
func (*Policy) Descriptor() ([]byte, []int) {
	return file_gateway_api_proto_rawDescGZIP(), []int{0}
}

func (x *Policy) GetMetadata() *Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Policy) GetTargetRefs() []*TargetRef {
	if x != nil {
		return x.TargetRefs
	}
	return nil
}

type Gateway struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Metadata         *Metadata              `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	GatewayClassName string                 `protobuf:"bytes,2,opt,name=gatewayClassName,proto3" json:"gatewayClassName,omitempty"`
	Listeners        []*Listener            `protobuf:"bytes,3,rep,name=listeners,proto3" json:"listeners,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Gateway) Reset() {
	*x = Gateway{}
	mi := &file_gateway_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Gateway) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Gateway) ProtoMessage() {}

func (x *Gateway) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Gateway.ProtoReflect.Descriptor instead.
func (*Gateway) Descriptor() ([]byte, []int) {
	return file_gateway_api_proto_rawDescGZIP(), []int{1}
}

func (x *Gateway) GetMetadata() *Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Gateway) GetGatewayClassName() string {
	if x != nil {
		return x.GatewayClassName
	}
	return ""
}

func (x *Gateway) GetListeners() []*Listener {
	if x != nil {
		return x.Listeners
	}
	return nil
}

type Metadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Group         string                 `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	Kind          string                 `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Namespace     string                 `protobuf:"bytes,4,opt,name=namespace,proto3" json:"namespace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Metadata) Reset() {
	*x = Metadata{}
	mi := &file_gateway_api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metadata) ProtoMessage() {}

func (x *Metadata) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metadata.ProtoReflect.Descriptor instead.
func (*Metadata) Descriptor() ([]byte, []int) {
	return file_gateway_api_proto_rawDescGZIP(), []int{2}
}

func (x *Metadata) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *Metadata) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Metadata) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Metadata) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

type Listener struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hostname      string                 `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Listener) Reset() {
	*x = Listener{}
	mi := &file_gateway_api_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Listener) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Listener) ProtoMessage() {}

func (x *Listener) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_api_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Listener.ProtoReflect.Descriptor instead.
func (*Listener) Descriptor() ([]byte, []int) {
	return file_gateway_api_proto_rawDescGZIP(), []int{3}
}

func (x *Listener) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

type TargetRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Group         string                 `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	Kind          string                 `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Namespace     string                 `protobuf:"bytes,4,opt,name=namespace,proto3" json:"namespace,omitempty"`
	SectionName   string                 `protobuf:"bytes,5,opt,name=sectionName,proto3" json:"sectionName,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TargetRef) Reset() {
	*x = TargetRef{}
	mi := &file_gateway_api_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TargetRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TargetRef) ProtoMessage() {}

func (x *TargetRef) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_api_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TargetRef.ProtoReflect.Descriptor instead.
func (*TargetRef) Descriptor() ([]byte, []int) {
	return file_gateway_api_proto_rawDescGZIP(), []int{4}
}

func (x *TargetRef) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *TargetRef) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *TargetRef) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TargetRef) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *TargetRef) GetSectionName() string {
	if x != nil {
		return x.SectionName
	}
	return ""
}

var File_gateway_api_proto protoreflect.FileDescriptor

const file_gateway_api_proto_rawDesc = "" +
	"\n" +
	"\x11gateway_api.proto\x12\vkuadrant.v0\"s\n" +
	"\x06Policy\x121\n" +
	"\bmetadata\x18\x01 \x01(\v2\x15.kuadrant.v0.MetadataR\bmetadata\x126\n" +
	"\n" +
	"targetRefs\x18\x02 \x03(\v2\x16.kuadrant.v0.TargetRefR\n" +
	"targetRefs\"\x9d\x01\n" +
	"\aGateway\x121\n" +
	"\bmetadata\x18\x01 \x01(\v2\x15.kuadrant.v0.MetadataR\bmetadata\x12*\n" +
	"\x10gatewayClassName\x18\x02 \x01(\tR\x10gatewayClassName\x123\n" +
	"\tlisteners\x18\x03 \x03(\v2\x15.kuadrant.v0.ListenerR\tlisteners\"f\n" +
	"\bMetadata\x12\x14\n" +
	"\x05group\x18\x01 \x01(\tR\x05group\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1c\n" +
	"\tnamespace\x18\x04 \x01(\tR\tnamespace\"&\n" +
	"\bListener\x12\x1a\n" +
	"\bhostname\x18\x01 \x01(\tR\bhostname\"\x89\x01\n" +
	"\tTargetRef\x12\x14\n" +
	"\x05group\x18\x01 \x01(\tR\x05group\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1c\n" +
	"\tnamespace\x18\x04 \x01(\tR\tnamespace\x12 \n" +
	"\vsectionName\x18\x05 \x01(\tR\vsectionNameB=Z;github.com/kuadrant/kuadrant-operator/pkg/extension/grpc/v0b\x06proto3"

var (
	file_gateway_api_proto_rawDescOnce sync.Once
	file_gateway_api_proto_rawDescData []byte
)

func file_gateway_api_proto_rawDescGZIP() []byte {
	file_gateway_api_proto_rawDescOnce.Do(func() {
		file_gateway_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gateway_api_proto_rawDesc), len(file_gateway_api_proto_rawDesc)))
	})
	return file_gateway_api_proto_rawDescData
}

var file_gateway_api_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_gateway_api_proto_goTypes = []any{
	(*Policy)(nil),    // 0: kuadrant.v0.Policy
	(*Gateway)(nil),   // 1: kuadrant.v0.Gateway
	(*Metadata)(nil),  // 2: kuadrant.v0.Metadata
	(*Listener)(nil),  // 3: kuadrant.v0.Listener
	(*TargetRef)(nil), // 4: kuadrant.v0.TargetRef
}
var file_gateway_api_proto_depIdxs = []int32{
	2, // 0: kuadrant.v0.Policy.metadata:type_name -> kuadrant.v0.Metadata
	4, // 1: kuadrant.v0.Policy.targetRefs:type_name -> kuadrant.v0.TargetRef
	2, // 2: kuadrant.v0.Gateway.metadata:type_name -> kuadrant.v0.Metadata
	3, // 3: kuadrant.v0.Gateway.listeners:type_name -> kuadrant.v0.Listener
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_gateway_api_proto_init() }
func file_gateway_api_proto_init() {
	if File_gateway_api_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gateway_api_proto_rawDesc), len(file_gateway_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_gateway_api_proto_goTypes,
		DependencyIndexes: file_gateway_api_proto_depIdxs,
		MessageInfos:      file_gateway_api_proto_msgTypes,
	}.Build()
	File_gateway_api_proto = out.File
	file_gateway_api_proto_goTypes = nil
	file_gateway_api_proto_depIdxs = nil
}
