// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: kuadrant.proto

package v0

import (
	v1alpha1 "google.golang.org/genproto/googleapis/api/expr/v1alpha1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The request message containing the time the request was dispatched.
type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Out           *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=out,proto3" json:"out,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_kuadrant_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kuadrant_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_kuadrant_proto_rawDescGZIP(), []int{0}
}

func (x *PingRequest) GetOut() *timestamppb.Timestamp {
	if x != nil {
		return x.Out
	}
	return nil
}

// The response message containing the time the request was received.
type PongResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	In            *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=in,proto3" json:"in,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PongResponse) Reset() {
	*x = PongResponse{}
	mi := &file_kuadrant_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PongResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PongResponse) ProtoMessage() {}

func (x *PongResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kuadrant_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PongResponse.ProtoReflect.Descriptor instead.
func (*PongResponse) Descriptor() ([]byte, []int) {
	return file_kuadrant_proto_rawDescGZIP(), []int{1}
}

func (x *PongResponse) GetIn() *timestamppb.Timestamp {
	if x != nil {
		return x.In
	}
	return nil
}

// evaluate the expression and whether or not to subscribe
type ResolveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Policy        *Policy                `protobuf:"bytes,1,opt,name=policy,proto3" json:"policy,omitempty"`
	Expression    string                 `protobuf:"bytes,2,opt,name=expression,proto3" json:"expression,omitempty"`
	Subscribe     bool                   `protobuf:"varint,3,opt,name=subscribe,proto3" json:"subscribe,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveRequest) Reset() {
	*x = ResolveRequest{}
	mi := &file_kuadrant_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveRequest) ProtoMessage() {}

func (x *ResolveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kuadrant_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveRequest.ProtoReflect.Descriptor instead.
func (*ResolveRequest) Descriptor() ([]byte, []int) {
	return file_kuadrant_proto_rawDescGZIP(), []int{2}
}

func (x *ResolveRequest) GetPolicy() *Policy {
	if x != nil {
		return x.Policy
	}
	return nil
}

func (x *ResolveRequest) GetExpression() string {
	if x != nil {
		return x.Expression
	}
	return ""
}

func (x *ResolveRequest) GetSubscribe() bool {
	if x != nil {
		return x.Subscribe
	}
	return false
}

// Return the result as a cel value
type ResolveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CelResult     *v1alpha1.Value        `protobuf:"bytes,1,opt,name=cel_result,json=celResult,proto3" json:"cel_result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveResponse) Reset() {
	*x = ResolveResponse{}
	mi := &file_kuadrant_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveResponse) ProtoMessage() {}

func (x *ResolveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kuadrant_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveResponse.ProtoReflect.Descriptor instead.
func (*ResolveResponse) Descriptor() ([]byte, []int) {
	return file_kuadrant_proto_rawDescGZIP(), []int{3}
}

func (x *ResolveResponse) GetCelResult() *v1alpha1.Value {
	if x != nil {
		return x.CelResult
	}
	return nil
}

// todo: define the message to be streamed back to the client
type Event struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      *Metadata              `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_kuadrant_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_kuadrant_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_kuadrant_proto_rawDescGZIP(), []int{4}
}

func (x *Event) GetMetadata() *Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

var File_kuadrant_proto protoreflect.FileDescriptor

const file_kuadrant_proto_rawDesc = "" +
	"\n" +
	"\x0ekuadrant.proto\x12\vkuadrant.v0\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x11gateway_api.proto\x1a\x1fgoogle/api/cel/expr/value.proto\";\n" +
	"\vPingRequest\x12,\n" +
	"\x03out\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x03out\":\n" +
	"\fPongResponse\x12*\n" +
	"\x02in\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x02in\"{\n" +
	"\x0eResolveRequest\x12+\n" +
	"\x06policy\x18\x01 \x01(\v2\x13.kuadrant.v0.PolicyR\x06policy\x12\x1e\n" +
	"\n" +
	"expression\x18\x02 \x01(\tR\n" +
	"expression\x12\x1c\n" +
	"\tsubscribe\x18\x03 \x01(\bR\tsubscribe\"Q\n" +
	"\x0fResolveResponse\x12>\n" +
	"\n" +
	"cel_result\x18\x01 \x01(\v2\x1f.google.api.expr.v1alpha1.ValueR\tcelResult\":\n" +
	"\x05Event\x121\n" +
	"\bmetadata\x18\x01 \x01(\v2\x15.kuadrant.v0.MetadataR\bmetadata2\xd6\x01\n" +
	"\x10ExtensionService\x12=\n" +
	"\x04Ping\x12\x18.kuadrant.v0.PingRequest\x1a\x19.kuadrant.v0.PongResponse\"\x00\x12;\n" +
	"\tSubscribe\x12\x16.google.protobuf.Empty\x1a\x12.kuadrant.v0.Event\"\x000\x01\x12F\n" +
	"\aResolve\x12\x1b.kuadrant.v0.ResolveRequest\x1a\x1c.kuadrant.v0.ResolveResponse\"\x00B=Z;github.com/kuadrant/kuadrant-operator/pkg/extension/grpc/v0b\x06proto3"

var (
	file_kuadrant_proto_rawDescOnce sync.Once
	file_kuadrant_proto_rawDescData []byte
)

func file_kuadrant_proto_rawDescGZIP() []byte {
	file_kuadrant_proto_rawDescOnce.Do(func() {
		file_kuadrant_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kuadrant_proto_rawDesc), len(file_kuadrant_proto_rawDesc)))
	})
	return file_kuadrant_proto_rawDescData
}

var file_kuadrant_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_kuadrant_proto_goTypes = []any{
	(*PingRequest)(nil),           // 0: kuadrant.v0.PingRequest
	(*PongResponse)(nil),          // 1: kuadrant.v0.PongResponse
	(*ResolveRequest)(nil),        // 2: kuadrant.v0.ResolveRequest
	(*ResolveResponse)(nil),       // 3: kuadrant.v0.ResolveResponse
	(*Event)(nil),                 // 4: kuadrant.v0.Event
	(*timestamppb.Timestamp)(nil), // 5: google.protobuf.Timestamp
	(*Policy)(nil),                // 6: kuadrant.v0.Policy
	(*v1alpha1.Value)(nil),        // 7: google.api.expr.v1alpha1.Value
	(*Metadata)(nil),              // 8: kuadrant.v0.Metadata
	(*emptypb.Empty)(nil),         // 9: google.protobuf.Empty
}
var file_kuadrant_proto_depIdxs = []int32{
	5, // 0: kuadrant.v0.PingRequest.out:type_name -> google.protobuf.Timestamp
	5, // 1: kuadrant.v0.PongResponse.in:type_name -> google.protobuf.Timestamp
	6, // 2: kuadrant.v0.ResolveRequest.policy:type_name -> kuadrant.v0.Policy
	7, // 3: kuadrant.v0.ResolveResponse.cel_result:type_name -> google.api.expr.v1alpha1.Value
	8, // 4: kuadrant.v0.Event.metadata:type_name -> kuadrant.v0.Metadata
	0, // 5: kuadrant.v0.ExtensionService.Ping:input_type -> kuadrant.v0.PingRequest
	9, // 6: kuadrant.v0.ExtensionService.Subscribe:input_type -> google.protobuf.Empty
	2, // 7: kuadrant.v0.ExtensionService.Resolve:input_type -> kuadrant.v0.ResolveRequest
	1, // 8: kuadrant.v0.ExtensionService.Ping:output_type -> kuadrant.v0.PongResponse
	4, // 9: kuadrant.v0.ExtensionService.Subscribe:output_type -> kuadrant.v0.Event
	3, // 10: kuadrant.v0.ExtensionService.Resolve:output_type -> kuadrant.v0.ResolveResponse
	8, // [8:11] is the sub-list for method output_type
	5, // [5:8] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_kuadrant_proto_init() }
func file_kuadrant_proto_init() {
	if File_kuadrant_proto != nil {
		return
	}
	file_gateway_api_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kuadrant_proto_rawDesc), len(file_kuadrant_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_kuadrant_proto_goTypes,
		DependencyIndexes: file_kuadrant_proto_depIdxs,
		MessageInfos:      file_kuadrant_proto_msgTypes,
	}.Build()
	File_kuadrant_proto = out.File
	file_kuadrant_proto_goTypes = nil
	file_kuadrant_proto_depIdxs = nil
}
