// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: kuadrant.proto

package v0

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The request message containing the time the request was dispatched.
type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Out           *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=out,proto3" json:"out,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_kuadrant_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kuadrant_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_kuadrant_proto_rawDescGZIP(), []int{0}
}

func (x *PingRequest) GetOut() *timestamppb.Timestamp {
	if x != nil {
		return x.Out
	}
	return nil
}

// The response message containing the time the request was received.
type PongResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	In            *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=in,proto3" json:"in,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PongResponse) Reset() {
	*x = PongResponse{}
	mi := &file_kuadrant_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PongResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PongResponse) ProtoMessage() {}

func (x *PongResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kuadrant_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PongResponse.ProtoReflect.Descriptor instead.
func (*PongResponse) Descriptor() ([]byte, []int) {
	return file_kuadrant_proto_rawDescGZIP(), []int{1}
}

func (x *PongResponse) GetIn() *timestamppb.Timestamp {
	if x != nil {
		return x.In
	}
	return nil
}

var File_kuadrant_proto protoreflect.FileDescriptor

const file_kuadrant_proto_rawDesc = "" +
	"\n" +
	"\x0ekuadrant.proto\x12\vkuadrant.v0\x1a\x1fgoogle/protobuf/timestamp.proto\";\n" +
	"\vPingRequest\x12,\n" +
	"\x03out\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x03out\":\n" +
	"\fPongResponse\x12*\n" +
	"\x02in\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x02in2\x97\x01\n" +
	"\x10ExtensionService\x12=\n" +
	"\x04Ping\x12\x18.kuadrant.v0.PingRequest\x1a\x19.kuadrant.v0.PongResponse\"\x00\x12D\n" +
	"\tSubscribe\x12\x18.kuadrant.v0.PingRequest\x1a\x19.kuadrant.v0.PongResponse\"\x000\x01B=Z;github.com/kuadrant/kuadrant-operator/pkg/extension/grpc/v0b\x06proto3"

var (
	file_kuadrant_proto_rawDescOnce sync.Once
	file_kuadrant_proto_rawDescData []byte
)

func file_kuadrant_proto_rawDescGZIP() []byte {
	file_kuadrant_proto_rawDescOnce.Do(func() {
		file_kuadrant_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kuadrant_proto_rawDesc), len(file_kuadrant_proto_rawDesc)))
	})
	return file_kuadrant_proto_rawDescData
}

var file_kuadrant_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_kuadrant_proto_goTypes = []any{
	(*PingRequest)(nil),           // 0: kuadrant.v0.PingRequest
	(*PongResponse)(nil),          // 1: kuadrant.v0.PongResponse
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_kuadrant_proto_depIdxs = []int32{
	2, // 0: kuadrant.v0.PingRequest.out:type_name -> google.protobuf.Timestamp
	2, // 1: kuadrant.v0.PongResponse.in:type_name -> google.protobuf.Timestamp
	0, // 2: kuadrant.v0.ExtensionService.Ping:input_type -> kuadrant.v0.PingRequest
	0, // 3: kuadrant.v0.ExtensionService.Subscribe:input_type -> kuadrant.v0.PingRequest
	1, // 4: kuadrant.v0.ExtensionService.Ping:output_type -> kuadrant.v0.PongResponse
	1, // 5: kuadrant.v0.ExtensionService.Subscribe:output_type -> kuadrant.v0.PongResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_kuadrant_proto_init() }
func file_kuadrant_proto_init() {
	if File_kuadrant_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kuadrant_proto_rawDesc), len(file_kuadrant_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_kuadrant_proto_goTypes,
		DependencyIndexes: file_kuadrant_proto_depIdxs,
		MessageInfos:      file_kuadrant_proto_msgTypes,
	}.Build()
	File_kuadrant_proto = out.File
	file_kuadrant_proto_goTypes = nil
	file_kuadrant_proto_depIdxs = nil
}
