apiVersion: apps/v1
kind: Deployment
metadata:
  name: llm-sim
  namespace: llm
  labels:
    app: llm-sim
spec:
  replicas: 1
  selector:
    matchLabels:
      app: llm-sim
  template:
    metadata:
      labels:
        app: llm-sim
    spec:
      containers:
      - name: simulator
        image: ghcr.io/llm-d/llm-d-inference-sim:v0.3.0
        args:
          - --model
          - Qwen/Qwen2.5-1.5B-Instruct
          - --port
          - "8000"
          - --lora-modules
          - "{\"name\":\"tweet-summary-0\"}"
          - "{\"name\":\"tweet-summary-1\"}"
        ports:
          - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: llm-sim
  namespace: llm
spec:
  selector:
    app: llm-sim
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
