apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "limitador-operator.fullname" . }}
  labels:
    {{- include "limitador-operator.labels" . | nindent 4 }}
    app: limitador-operator
spec:
  {{- if .Values.replicas }}
  replicas: {{ .Values.replicas }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "limitador-operator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "limitador-operator.selectorLabels" . | nindent 8 }}
        app: limitador-operator
    spec:
      securityContext:
        runAsNonRoot: true
      serviceAccountName: {{ include "limitador-operator.serviceAccountName" . }}
      terminationGracePeriodSeconds: 10
      containers:
      - name: manager
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command:
        - /manager
        args:
        - --leader-elect
        {{- if .Values.limitadorImage }}
        env:
        - name: RELATED_IMAGE_LIMITADOR
          value: {{ .Values.limitadorImage }}
        {{- end }}
        ports:
        - name: metrics
          containerPort: 8080
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        securityContext:
          allowPrivilegeEscalation: false
        {{- with .Values.resources }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}
