{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "limitador-operator.serviceAccountName" . }}
  labels:
    {{- include "limitador-operator.labels" . | nindent 4 }}
{{- end }}
