apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: my-route-inmemory
  labels:
    kuadrant.io/test-dns-provider: inmemory
spec:
  parentRefs:
    - kind: Gateway
      name: prod-web-istio-inmemory
  hostnames:
    - "myapp.kuadrant.local"
    - "myapp2.kuadrant.local"
  rules:
    - backendRefs:
        - name: echo
          port: 8080
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: my-route-aws
  labels:
    kuadrant.io/test-dns-provider: aws
spec:
  parentRefs:
    - kind: Gateway
      name: prod-web-istio-aws
  hostnames:
    - "myapp.mn.hcpapps.net"
    - "myapp2.mn.hcpapps.net"
  rules:
    - backendRefs:
        - name: echo
          port: 8080
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: my-route-gcp
  labels:
    kuadrant.io/test-dns-provider: gcp
spec:
  parentRefs:
    - kind: Gateway
      name: prod-web-istio-gcp
  hostnames:
    - "myapp.mn.google.hcpapps.net"
    - "myapp2.mn.google.hcpapps.net"
  rules:
    - backendRefs:
        - name: echo
          port: 8080
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: my-route-azure
  labels:
    kuadrant.io/test-dns-provider: azure
spec:
  parentRefs:
    - kind: Gateway
      name: prod-web-istio-azure
  hostnames:
    - "myapp.mn.azure.hcpapps.net"
    - "myapp2.mn.azure.hcpapps.net"
  rules:
    - backendRefs:
        - name: echo
          port: 8080
