apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: istiod
  namespace: gateway-system
spec:
  namespaceSelector:
    matchNames:
    - gateway-system
  selector:
    matchLabels:
      app: istiod
  endpoints:
  - port: http-monitoring

