apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: kuadrant-operator
  namespace: kuadrant-system
spec:
  podSelector:
    matchLabels:
      app: kuadrant
      control-plane: controller-manager
  policyTypes:
    - Ingress
    - Egress
  ingress:
    # gRPC for OOP extensions
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kuadrant-system
      ports:
        - protocol: TCP
          port: 50051
    # wasm plugin binary fetch
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: gateway-system
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: istio-system
      ports:
        - protocol: TCP
          port: 8082
  egress:
    # OTLP trace export
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: observability
      ports:
        - protocol: TCP
          port: 4317
    # DNS resolution
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: openshift-dns
      ports:
        - protocol: UDP
          port: 5353
