name: Automated Release Operator

on:
  workflow_dispatch:
    inputs:
      gitRef:
        description: Commit SHA, tag or branch name (usually main branch)
        required: true
      kuadrantOperatorVersion:
        description: Kuadrant Operator version (X.Y.Z-<pre-release id>)
        default: 0.0.0
        type: string
      authorinoOperatorVersion:
        description: Authorino Operator bundle version (X.Y.Z)
        default: 0.0.0
        type: string
      limitadorOperatorVersion:
        description: Limitador Operator bundle version (X.Y.Z)
        default: 0.0.0
        type: string
      dnsOperatorVersion:
        description: DNS Operator bundle version (X.Y.Z)
        default: 0.0.0
        type: string
      wasmShimVersion:
        description: WASM Shim version (X.Y.Z)
        default: 0.0.0
        type: string
      consolePluginVersion:
        description: ConsolePlugin version (X.Y.Z)
        default: "latest"
        type: string

jobs:
  build:
    name: Release operator
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.21.x
        uses: actions/setup-go@v4
        with:
          go-version: 1.21.x
        id: go
      - name: Checkout code at git ref
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.gitRef }}
          token: ${{ secrets.KUADRANT_DEV_PAT }}

      - name: Install yq tool
        run: |
          make yq

      - name: Create release branch(es)
        run: |
          cr_version = ${{ inputs.kuadrantOperatorVersion }}
          base_branch = release-v${${cr_version%%-*}%.*}
          echo BASE_BRANCH=${base_branch} >> $GITHUB_ENV
          
          if git ls-remote --exit-code --heads origin ${base_branch} ; then
            echo "Base branch ${base_branch} already exists"
          else
            echo "Creating branch ${base_branch}"
            git checkout -b ${base_branch}
            git push origin
          fi
          
          echo "Creating candidate release branch"
          git checkout -b release-v${cr_version}
      

      - name: Prepare release
        run: |
          echo "Updating release.yaml with desired versions"
          
          VERSION=${{ inputs.kuadrantOperatorVersion }} \
          AUTHORINO_OPERATOR_VERSION=${{ inputs.authorinoOperatorVersion }} \
          DNS_OPERATOR_VERSION=${{ inputs.dnsOperatorVersion }} \
          LIMITADOR_OPERATOR_VERSION=${{ inputs.limitadorOperatorVersion }} \
          CONSOLE_PLUGIN_VERSION=${{ inputs.consolePluginImageURL }} \
          WASM_SHIM_VERSION=${{ inputs.wasmShimVersion }} \
  
          yq eval '.version = strenv(VERSION) | \
                  .dependencies.authorino-operator = strenv(AUTHORINO_OPERATOR_VERSION) | \
                  .dependencies.dns-operator = strenv(DNS_OPERATOR_VERSION) | \
                  .dependencies.limitador-operator = strenv(LIMITADOR_OPERATOR_VERSION) | \
                  .dependencies.console-plugin = strenv(CONSOLE_PLUGIN_VERSION) | \
                  .dependencies.wasm-shim = strenv(WASM_SHIM_VERSION) | \
                  ' -i ./release.yaml
          
          echo "Running make target `prepare-release`"
          
          make prepare-release

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.KUADRANT_DEV_PAT }}
          commit-message: Prepare release ${{ inputs.kuadrantOperatorVersion }}
          committer: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          author: ${{ github.actor }} <${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com>
          signoff: true
          base: ${{ env.BASE_BRANCH }}
          branch: release-v${{ inputs.kuadrantOperatorVersion }}
          delete-branch: true
          title: '[Release] Kuadrant Operator v${{ inputs.kuadrantOperatorVersion }}'
          body: |
            The following PR for the release candidate of Kuadrant Operator version ${{ inputs.kuadrantOperatorVersion }} includes:
            - Authorino Operator version ${{ inputs.authorinoOperatorVersion }}
            - DNS Operator version ${{ inputs.dnsOperatorVersion }}
            - Limitador Operator version ${{ inputs.limitadorOperatorVersion }}
            - Console Plugin version ${{ inputs.consolePluginImageURL }}
            - WASM Shim version ${{ inputs.wasmShimVersion }}
            
            Auto-generated by [create-pull-request][1]

            [1]: https://github.com/peter-evans/create-pull-request
          team-reviewers: |
            Kuadrant/developers
            Kuadrant/qe
          draft: false
