name: Build images for release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  workflow-build:
    steps:
    - name: Sets release version and tag
      run: |
        echo REF_NAME=${GITHUB_REF_NAME/\//-}
        echo "VERSION=${REF_NAME/v/}" >> $GITHUB_ENV
    - name: Calls build-images-base workflow
      uses: ./.github/workflows/build-images-base.yaml
      secrets: inherit
      with:
        kuadrantOperatorVersion: ${VERSION}
        kuadrantOperatorTag: ${VERSION}
