name: Build Images

on:
  workflow_call:
    inputs:
      kuadrantOperatorTag:
        description: Kuadrant Operator tag
        default: latest
        type: string
      kuadrantOperatorVersion:
        description: Kuadrant Operator version
        default: 0.0.0
        type: string
      authorinoBundleImg:
        description: Authorino Operator bundle image url
        default: quay.io/kuadrant/authorino-operator-bundle:latest
        type: string
      limitadorBundleImg:
        description: Limitador Operator bundle image url
        default: quay.io/kuadrant/limitador-operator-bundle:latest
        type: string
      dnsOperatorBundleImg:
        description: DNS Operator bundle image url
        default: quay.io/kuadrant/dns-operator-bundle:latest
        type: string
      relatedImageWasmShim:
        description: Related image WASM Shim
        default: quay.io/kuadrant/wasm-shim:latest
        type: string
      relatedImageDeveloperPortalController:
        description: Related image Developer portal controller
        default: quay.io/kuadrant/developer-portal-controller:latest
        type: string
      relatedImageConsolePluginLatest:
        description: Related image ConsolePlugin latest (PatternFly 6)
        default: quay.io/kuadrant/console-plugin:latest
        type: string
      relatedImageConsolePluginPF5:
        description: Related image ConsolePlugin v0.1.5 (PatternFly 5)
        default: quay.io/kuadrant/console-plugin:v0.1.5
        type: string
      consolePluginImageURL:
        description: ConsolePlugin image URL
        default: "quay.io/kuadrant/console-plugin:latest"
        type: string
      channels:
        description: Bundle and catalog channels, comma separated
        default: preview
        type: string
      defaultChannel:
        description: Bundle default channel
        default: preview
        type: string
      quayImageExpiry:
        description: When to expire the built quay images. The time values could be something like 1h, 2d, 3w for hours, days, and weeks, respectively, from the time the image is built.
        default: never
        type: string
  workflow_dispatch:
    inputs:
      kuadrantOperatorTag:
        description: Kuadrant Operator tag
        default: latest
        type: string
      kuadrantOperatorVersion:
        description: Kuadrant Operator version
        default: 0.0.0
        type: string
      authorinoBundleImg:
        description: Authorino Operator bundle image url
        default: quay.io/kuadrant/authorino-operator-bundle:latest
        type: string
      limitadorBundleImg:
        description: Limitador Operator bundle image url
        default: quay.io/kuadrant/limitador-operator-bundle:latest
        type: string
      dnsOperatorBundleImg:
        description: DNS Operator bundle image url
        default: quay.io/kuadrant/dns-operator-bundle:latest
        type: string
      relatedImageWasmShim:
        description: Related image WASM Shim
        default: quay.io/kuadrant/wasm-shim:latest
        type: string
      relatedImageDeveloperPortalController:
        description: Related image Developer portal controller
        default: quay.io/kuadrant/developer-portal-controller:latest
        type: string
      relatedImageConsolePluginLatest:
        description: Related image ConsolePlugin latest (PatternFly 6)
        default: quay.io/kuadrant/console-plugin:latest
        type: string
      relatedImageConsolePluginPF5:
        description: Related image ConsolePlugin v0.1.5 (PatternFly 5)
        default: quay.io/kuadrant/console-plugin:v0.1.5
        type: string
      consolePluginImageURL:
        description: ConsolePlugin image URL
        default: "quay.io/kuadrant/console-plugin:latest"
        type: string
      channels:
        description: Bundle and catalog channels, comma separated
        default: preview
        type: string
      defaultChannel:
        description: Bundle default channel
        default: preview
        type: string
      quayImageExpiry:
        description: When to expire the built quay images. The time values could be something like 1h, 2d, 3w for hours, days, and weeks, respectively, from the time the image is built.
        default: never
        type: string

env:
  IMG_REGISTRY_HOST: quay.io
  IMG_REGISTRY_ORG: kuadrant
  MAIN_BRANCH_NAME: main
  OPERATOR_NAME: kuadrant-operator
  QUAY_IMAGE_EXPIRY: ${{ inputs.quayImageExpiry }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v5
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to container registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.IMG_REGISTRY_USERNAME }}
          password: ${{ secrets.IMG_REGISTRY_TOKEN }}
          registry: ${{ env.IMG_REGISTRY_HOST }}
      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMG_REGISTRY_HOST }}/${{ env.IMG_REGISTRY_ORG }}/${{ env.OPERATOR_NAME }}
          tags: |
            type=raw,value=${{ inputs.kuadrantOperatorTag }}
      - name: Build and Push Image
        id: build-image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64,linux/s390x
          push: true
          provenance: false
          tags: ${{ steps.meta.outputs.tags }}
          build-args: |
            QUAY_IMAGE_EXPIRY=${{ inputs.quayImageExpiry }}
            GIT_SHA=${{ github.sha }}
            DIRTY=false
            VERSION=${{ inputs.kuadrantOperatorVersion }}
      - name: Print Image URL
        run: |
          echo "Image(s) pushed:"
          echo "${{ steps.meta.outputs.tags }}"

  build-bundle:
    needs: build
    name: Build Bundle
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v5
      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
        id: go
      - name: Run make bundle
        id: make-bundle
        run: |
          make bundle \
            IMG=${{ env.IMG_REGISTRY_HOST }}/${{ env.IMG_REGISTRY_ORG }}/${{ env.OPERATOR_NAME }}:${{ inputs.kuadrantOperatorTag }} \
            VERSION=${{ inputs.kuadrantOperatorVersion }} \
            AUTHORINO_OPERATOR_BUNDLE_IMG=${{ inputs.authorinoBundleImg }} \
            LIMITADOR_OPERATOR_BUNDLE_IMG=${{ inputs.limitadorBundleImg }} \
            DNS_OPERATOR_BUNDLE_IMG=${{ inputs.dnsOperatorBundleImg }} \
            RELATED_IMAGE_WASMSHIM=${{ inputs.relatedImageWasmShim }} \
            RELATED_IMAGE_DEVELOPERPORTAL=${{ inputs.relatedImageWasmShim }} \
            RELATED_IMAGE_CONSOLE_PLUGIN_LATEST=${{ inputs.relatedImageConsolePluginLatest}} \
            RELATED_IMAGE_CONSOLE_PLUGIN_PF5=${{ inputs.relatedImageConsolePluginPF5}} \
            DEFAULT_CHANNEL=${{ inputs.defaultChannel }} \
            CHANNELS=${{ inputs.channels }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to container registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.IMG_REGISTRY_USERNAME }}
          password: ${{ secrets.IMG_REGISTRY_TOKEN }}
          registry: ${{ env.IMG_REGISTRY_HOST }}
      - name: Extract metadata
        id: bundle-meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMG_REGISTRY_HOST }}/${{ env.IMG_REGISTRY_ORG }}/${{ env.OPERATOR_NAME }}-bundle
          tags: |
            type=raw,value=${{ inputs.kuadrantOperatorTag }}
      - name: Build and Push Bundle Image
        id: build-bundle-image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./bundle.Dockerfile
          platforms: linux/amd64,linux/arm64,linux/s390x
          push: true
          provenance: false
          tags: ${{ steps.bundle-meta.outputs.tags }}
          build-args: QUAY_IMAGE_EXPIRY=${{ inputs.quayImageExpiry }}
      - name: Print Image URL
        run: |
          echo "Image(s) pushed:"
          echo "${{ steps.bundle-meta.outputs.tags }}"

  build-catalog:
    name: Build Catalog
    needs: [build, build-bundle]
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
        id: go
      - name: Generate Catalog Content
        run: |
          make catalog \
            BUNDLE_IMG=${{ env.IMG_REGISTRY_HOST }}/${{ env.IMG_REGISTRY_ORG }}/${{ env.OPERATOR_NAME }}-bundle:${{ inputs.kuadrantOperatorTag }} \
            AUTHORINO_OPERATOR_BUNDLE_IMG=${{ inputs.authorinoBundleImg }} \
            LIMITADOR_OPERATOR_BUNDLE_IMG=${{ inputs.limitadorBundleImg }} \
            DNS_OPERATOR_BUNDLE_IMG=${{ inputs.dnsOperatorBundleImg }} \
            CHANNEL=${{ inputs.defaultChannel }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to container registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.IMG_REGISTRY_USERNAME }}
          password: ${{ secrets.IMG_REGISTRY_TOKEN }}
          registry: ${{ env.IMG_REGISTRY_HOST }}
      - name: Extract metadata
        id: catalog-meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMG_REGISTRY_HOST }}/${{ env.IMG_REGISTRY_ORG }}/${{ env.OPERATOR_NAME }}-catalog
          tags: |
            type=raw,value=${{ inputs.kuadrantOperatorTag }}
      - name: Build and Push Catalog Image
        id: build-catalog-image
        uses: docker/build-push-action@v5
        with:
          context: ./catalog
          file: ./catalog/kuadrant-operator-catalog.Dockerfile
          platforms: linux/amd64,linux/arm64,linux/s390x
          push: true
          provenance: false
          tags: ${{ steps.catalog-meta.outputs.tags }}
          # The Quay image expiry label for the generated catalog Dockerfile is set via opm, using the value set in the QUAY_IMAGE_EXPIRY environment variable
      - name: Print Image URL
        run: |
          echo "Image(s) pushed:"
          echo "${{ steps.catalog-meta.outputs.tags }}"
