name: Build images for branches

on:
  push:
    branches:
      - "*"
      - "!main"
  workflow_dispatch: {}

jobs:
  workflow-build:
    name: Calls build-images-base workflow
    uses: ./.github/workflows/build-images-base.yaml
    secrets: inherit
    with:
      kuadrantOperatorVersion: 0.0.0
      kuadrantOperatorTag: ${{ github.ref_name }}
      quayImageExpiry: 1w
