name: Build images for main branch

on:
  push:
    branches: ['main']

jobs:
  workflow-build:
    name: Calls build-images-base workflow
    uses: ./.github/workflows/build-images-base.yaml
    secrets: inherit
