name: Schedule build with latest image SHA versions

on:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  workflow-build:
    name: Calls build-images-base workflow
    uses: ./.github/workflows/build-images-base.yaml
    secrets: inherit
    with:
      kuadrantOperatorVersion: ${{ github.sha }}
      kuadrantOperatorTag: ${{ github.sha }}
      authorinoOperatorBundleVersion: ${{ vars.AUTHORINO_OPERATOR_BUNDLE_SHA }}
      limitadorOperatorBundleVersion: ${{ vars.LIMITADOR_OPERATOR_BUNDLE_SHA }}
      wasmShimVersion: ${{ vars.WASM_SHIM_SHA }}
