name: Schedule nightly build with latest image SHA versions

on:
  schedule:
    - cron: '0 1 * * *'

jobs:
  workflow-build:
    name: Calls build-images-base workflow
    uses: ./.github/workflows/build-images-base.yaml
    secrets: inherit
    with:
      kuadrantOperatorVersion: ${{ github.sha }}
      kuadrantOperatorTag: nightly-$(date +'%d-%m-%Y')
      authorinoOperatorVersion: ${{ vars.AUTHORINO_OPERATOR_SHA }}
      limitadorOperatorVersion: ${{ vars.LIMITADOR_OPERATOR_SHA }}
      policyControllerVersion: ${{ vars.POLICY_CONTROLLER_SHA }}
      wasmShimVersion: ${{ vars.WASM_SHIM_SHA }}
