name: Build images for dev branches

on:
  push:
    branches: ['*']

jobs:
  workflow-build:
    if: github.ref_name != 'main' && !startsWith(github.ref, 'refs/tags/v')
    name: Calls build-images-base workflow
    uses: ./.github/workflows/build-images-base.yaml
    secrets: inherit
    with:
      kuadrantOperatorVersion: ${{ github.ref_name }}
      kuadrantOperatorTag: ${{ github.ref_name }}
      # Conditionally set quayImageExpiry to expire quay images only for non-release branches
      quayImageExpiry: ${{ startsWith(github.ref_name, 'release') && 'never' || '1w' }}