name: Release Validation

on:
  pull_request:
    types:
    - opened
    branches:
      - 'release-v[0-9]+.[0-9]+'
  workflow_dispatch: {}

jobs:
  build:
    name: Validate release data 
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.22.x
        uses: actions/setup-go@v4
        with:
          go-version: 1.22.x
        id: go
      - name: Checkout code at git ref
        uses: actions/checkout@v4
      - name: Check bundles and manifests
        run: make verify-prepare-release
