name: Update dependencies image versions

on:
  push:
    branches: ['**']
  schedule:
    - cron: '0 0 * * *'
  repository_dispatch: {}

env:
  IMG_TAGS: ${{ github.sha }}
  IMG_REGISTRY_HOST: quay.io
  IMG_REGISTRY_ORG: kuadrant
  MAIN_BRANCH_NAME: main
  OPERATOR_NAME: kuadrant-operator

jobs:
  get-latest-sha:
    name: Get projects latest SHA
    runs-on: ubuntu-latest
    permissions:
      actions: write
    strategy:
      fail-fast: true
      matrix:
        repository:
          - authorino-operator-bundle
          - limitador-operator-bundle
          - wasm-shim
    steps:
      - name: Fetch dependencies images list
        id: fetch
        uses: fjogeleit/http-request-action@master
        with:
          method: 'GET'
          url: https://quay.io/api/v1/repository/kuadrant/${{ matrix.repository }}?includeTags=true
      - name: Parse the list to get the last SHA
        id: parse
        run: |
          echo "sha=$(echo '${{ steps.fetch.outputs.response }}' | jq -c -r '.tags | keys_unsorted | .[] | select(.|test("[0-9a-f]{5,40}"))' | jq -Rn '[inputs]' | jq -c -r '.[0]')" >> $GITHUB_OUTPUT
      - name: Update stored variable
        id: update
        run: |
          var=$(echo ${{ matrix.repository }} | sed -E 's/-/_/;s/[a-z]/\U&/g')_SHA
          sha=${{ steps.parse.outputs.sha }}
          curl -L -X PATCH 'https://api.github.com/repos/kuadrant/kuadrant-operator/actions/variables/$var' -H "X-GitHub-Api-Version: 2022-11-28" -H 'Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' -H 'Accept: application/vnd.github+json' -d '{ "value": "$sha" }'
