apiVersion: v1
kind: ServiceAccount
metadata:
  name: grafana-monitoring
  namespace: monitoring
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: grafana-cluster-monitoring-view
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-monitoring-view
subjects:
  - kind: ServiceAccount
    name: grafana-monitoring
    namespace: monitoring
---
apiVersion: v1
kind: Secret
metadata:
  name: grafana-monitoring-token
  namespace: monitoring
  annotations:
    kubernetes.io/service-account.name: grafana-monitoring
type: kubernetes.io/service-account-token
